export const PERMISSIONS = {
  APPEAL: 'APPEAL',
  HF: 'HF',
  IRS: 'IRS',
  EQUIPMENT: 'EQUIPMENT',
  REGISTRY: 'REGISTRY',
  ATTESTATION: 'ATTESTATION',
  ACCREDITATION: 'ACCREDITATION',
  CADASTRE: 'CADASTRE',
  PERMITS: 'PERMITS',
};
