import { TemplateType } from './types'

/**
 * How a template type is written for a reader. It describes the entity's own
 * enum, so it lives here rather than in the admin feature - the entity's card
 * needs it, and an entity must not reach into a feature for it.
 */
const TEMPLATE_TYPE_MAP: Record<TemplateType, string> = {
  [TemplateType.IRS_APPEAL]: 'INM arizalari',
  [TemplateType.XICHO_APPEAL]: 'XICHO arizalari',
  [TemplateType.EQUIPMENT_APPEAL]: 'Qurilma arizalari',
  [TemplateType.ATTESTATION_LEADER_APPEAL]: 'ATTESTATION_LEADER_APPEAL',
  [TemplateType.ATTESTATION_EMPLOYEE_APPEAL]: 'ATTESTATION_EMPLOYEE_APPEAL',
  [TemplateType.CADASTRE_PASSPORT_APPEAL]: 'CADASTRE_PASSPORT_APPEAL',
  [TemplateType.ATTRACTION_PASSPORT_APPEAL]: 'ATTRACTION_PASSPORT_APPEAL',
  [TemplateType.DECLARATION_APPEAL]: 'DECLARATION_APPEAL',
  [TemplateType.ACCREDITATION_APPEAL]: 'ACCREDITATION_APPEAL',
  [TemplateType.RE_ACCREDITATION_APPEAL]: 'RE_ACCREDITATION_APPEAL',
  [TemplateType.EXPEND_ACCREDITATION_APPEAL]: 'EXPEND_ACCREDITATION_APPEAL',
  [TemplateType.EXPERTISE_CONCLUSION_APPEAL]: 'EXPERTISE_CONCLUSION_APPEAL',
  [TemplateType.REGISTRY_HF]: 'REGISTRY_HF',
  [TemplateType.REGISTRY_EQUIPMENT]: 'REGISTRY_EQUIPMENT',
  [TemplateType.REGISTRY_ATTRACTION]: 'REGISTRY_ATTRACTION',
  [TemplateType.REGISTRY_ATTRACTION_PASSPORT]: 'REGISTRY_ATTRACTION_PASSPORT',
  [TemplateType.REPLY_HF_APPEAL]: 'REPLY_HF_APPEAL',
  [TemplateType.REPLY_IRS_APPEAL]: 'REPLY_IRS_APPEAL',
  [TemplateType.REPLY_EQUIPMENT_APPEAL]: 'REPLY_EQUIPMENT_APPEAL',
  [TemplateType.REPLY_ATTRACTION_PASSPORT_APPEAL]: 'REPLY_ATTRACTION_PASSPORT_APPEAL',
  [TemplateType.REPLY_INSPECTION_REPORT]: 'REPLY_INSPECTION_REPORT',
  [TemplateType.REJECT_APPEAL]: 'REJECT_APPEAL',
  [TemplateType.REPLY_COMMITTEE_TO_APPEAL]: 'REPLY_COMMITTEE_TO_APPEAL',
  [TemplateType.REPLY_REGIONAL_TO_APPEAL]: 'REPLY_REGIONAL_TO_APPEAL',
  [TemplateType.REPLY_ACCEPT_CADASTRE_PASSPORT_APPEAL]: 'REPLY_ACCEPT_CADASTRE_PASSPORT_APPEAL',
  [TemplateType.REPLY_ACCEPT_DECLARATION_APPEAL]: 'REPLY_ACCEPT_DECLARATION_APPEAL',
  [TemplateType.REPLY_REJECT_CADASTRE_PASSPORT_APPEAL]: 'REPLY_REJECT_CADASTRE_PASSPORT_APPEAL',
  [TemplateType.REPLY_REJECT_DECLARATION_APPEAL]: 'REPLY_REJECT_DECLARATION_APPEAL',
} as const

export const getTemplateType = (type: TemplateType): string => TEMPLATE_TYPE_MAP[type] || 'Ariza'
