export interface Template {
  id: number;
  name: string;
  createdAt: string;
  type: TemplateType;
  description: string;
  content: string | null;
  updatedAt: string | null;
}

export type TemplateFormDTO = Omit<Template, 'id' | 'updated_at'>;

export interface TemplateCardProps {
  template: Template;
  onEdit?: (id: number) => void;
}

export enum TemplateType {
  // Appeal
  IRS_APPEAL = 'IRS_APPEAL',
  XICHO_APPEAL = 'XICHO_APPEAL',
  EQUIPMENT_APPEAL = 'EQUIPMENT_APPEAL',
  ATTRACTION_PASSPORT_APPEAL = 'ATTRACTION_PASSPORT_APPEAL',
  ATTESTATION_LEADER_APPEAL = 'ATTESTATION_LEADER_APPEAL',
  ATTESTATION_EMPLOYEE_APPEAL = 'ATTESTATION_EMPLOYEE_APPEAL',
  CADASTRE_PASSPORT_APPEAL = 'CADASTRE_PASSPORT_APPEAL',
  DECLARATION_APPEAL = 'DECLARATION_APPEAL',
  ACCREDITATION_APPEAL = 'ACCREDITATION_APPEAL',
  RE_ACCREDITATION_APPEAL = 'RE_ACCREDITATION_APPEAL',
  EXPEND_ACCREDITATION_APPEAL = 'EXPEND_ACCREDITATION_APPEAL',
  EXPERTISE_CONCLUSION_APPEAL = 'EXPERTISE_CONCLUSION_APPEAL',

  // Reestr
  REGISTRY_HF = 'REGISTRY_HF',
  REGISTRY_EQUIPMENT = 'REGISTRY_EQUIPMENT',
  REGISTRY_ATTRACTION = 'REGISTRY_ATTRACTION',
  REGISTRY_ATTRACTION_PASSPORT = 'REGISTRY_ATTRACTION_PASSPORT',

  // Inspektor javob xati ( Ma'lumotnoma )
  REPLY_HF_APPEAL = 'REPLY_HF_APPEAL',
  REPLY_IRS_APPEAL = 'REPLY_IRS_APPEAL',
  REPLY_EQUIPMENT_APPEAL = 'REPLY_EQUIPMENT_APPEAL',
  REPLY_ATTRACTION_PASSPORT_APPEAL = 'REPLY_ATTRACTION_PASSPORT_APPEAL',
  REPLY_INSPECTION_REPORT = 'REPLY_INSPECTION_REPORT',

  // Arizani rad etish
  REJECT_APPEAL = 'REJECT_APPEAL',

  // Attestatsiyaga Qo'mita va Huduiy bo'lim javob xati
  REPLY_COMMITTEE_TO_APPEAL = 'REPLY_COMMITTEE_TO_APPEAL',
  REPLY_REGIONAL_TO_APPEAL = 'REPLY_REGIONAL_TO_APPEAL',

  //Kadastrga qo'mita javob xati
  REPLY_ACCEPT_CADASTRE_PASSPORT_APPEAL = 'REPLY_ACCEPT_CADASTRE_PASSPORT_APPEAL',
  REPLY_ACCEPT_DECLARATION_APPEAL = 'REPLY_ACCEPT_DECLARATION_APPEAL',
  REPLY_REJECT_CADASTRE_PASSPORT_APPEAL = 'REPLY_REJECT_CADASTRE_PASSPORT_APPEAL',
  REPLY_REJECT_DECLARATION_APPEAL = 'REPLY_REJECT_DECLARATION_APPEAL',
}
