export const APPLICATION_CARDS = [
  {
    id: 1,
    title: 'Хавфли объект ва қурилмаларни рўйхатга олиш',
    description: 'Хавфли объектларни давлат рўйхатига киритиш учун ариза',
    category: 'registration',
    icon: 'documentAdd',
    isHighlighted: true,
  },
  {
    id: 2,
    title: 'Хавфли объект ва қурилмаларни рўйхатдан чиқариш',
    description: 'Объектларни рўйхатдан чиқариш учун ариза',
    category: 'registration',
    icon: 'documentRemove',
  },
  {
    id: 3,
    title: 'Хавфли объект ва қурилмаларни қайта рўйхатдан ўтказиш',
    description: 'Объектларни қайта рўйхатдан ўтказиш учун ариза',
    category: 'registration',
    icon: 'documentRefresh',
  },
  {
    id: 4,
    title: 'Босим остида ишловчи идишни рўйхатга олиш',
    description: 'Босим остида ишлайдиган идишларни рўйхатга олиш',
    category: 'equipment',
    icon: 'pressureVessel',
  },
  {
    id: 5,
    title: 'Буғқозонни рўйхатга олиш',
    description: 'Буғ қозонларини рўйхатга олиш учун ариза',
    category: 'equipment',
    icon: 'boiler',
  },
  {
    id: 6,
    title: 'Лифтни рўйхатга олиш',
    description: 'Лифт қурилмаларини рўйхатга олиш учун ариза',
    category: 'transport',
    icon: 'elevator',
  },
  {
    id: 7,
    title: 'Эскалаторни рўйхатга олиш',
    description: 'Эскалатор қурилмаларини рўйхатга олиш',
    category: 'transport',
    icon: 'escalator',
  },
  {
    id: 8,
    title: 'Аттракцион паспортини рўйхатга олиш',
    description: 'Аттракцион паспортларини расмийлаштириш',
    category: 'other',
    icon: 'passport',
    isNew: true,
  },
  {
    id: 9,
    title: 'Аттракционни рўйхатга олиш',
    description: 'Аттракцион қурилмаларини рўйхатга олиш',
    category: 'other',
    icon: 'attraction',
  },
  {
    id: 10,
    title: 'Кранни рўйхатга олиш',
    description: 'Кран қурилмаларини рўйхатга олиш',
    category: 'transport',
    icon: 'crane',
  },
  {
    id: 11,
    title: 'Қувурни рўйхатга олиш',
    description: 'Қувурларни рўйхатга олиш учун ариза',
    category: 'equipment',
    icon: 'pipeSystem',
  },
];
