import { ApplicationTypeEnum } from '@/entities/create-application'; // Loyihangizdagi ApplicationTypeEnum importi

interface FieldLabelPair {
  label: string;
  value: string; // fieldName
}

type AppealTypeLabelMapping = {
  [key in ApplicationTypeEnum]?: {
    orderedFields: string[]; // Maydonlarning tartiblangan ro'yxati
    labels: {
      [fieldName: string]: string;
    };
  };
};

// Umumiy maydonlar uchun labellar (EquipmentAppealDto va boshqalardan)
const commonEquipmentAppealLabels: { [fieldName: string]: string } = {
  phoneNumber: 'Telefon raqami',
  hazardousFacilityId: 'XICHOʻ', // Rasmda "XICHO nomi" yoki formda "XICHO'ni tanlang" edi, qisqartirildi
  childEquipmentId: 'Qurilma turi', // Umumiy, har bir formda o'ziga xos bo'ladi
  factoryNumber: 'Zavod raqami',
  model: 'Model, marka',
  factory: 'Ishlab chiqargan zavod nomi',
  location: 'Geolokatsiya (X,Y)',
  manufacturedAt: 'Ishlab chiqarilgan sana',
  regionId: 'Joylashgan viloyat',
  districtId: 'Joylashgan tuman',
  address: 'Joylashgan manzil',
  partialCheckDate: 'Qisman texnik ko‘rik sanasi',
  fullCheckDate: 'To‘liq texnik ko‘rik sanasi',
  nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
  labelPath: 'Qurilmaning birkasi bilan surati', // Umumiy, har bir formda o'ziga xos bo'ladi
  saleContractPath: 'Sotib olish-sotish shartnomasi fayli',
  equipmentCertPath: 'Qurilma sertifikati fayli',
  assignmentDecreePath: 'Masʼul shaxs tayinlanganligi to‘g‘risida buyruq fayli',
  expertisePath: 'Ekspertiza loyihasi fayli',
  installationCertPath: 'Montaj guvohnomasi fayli',
  additionalFilePath: 'Qo‘shimcha maʼlumotlar',
  email: 'Elektron pochta manzili', // EquipmentAppealDto da yo'q, lekin HfAppealDto da bor
};

const appealLabelMappings: AppealTypeLabelMapping = {
  [ApplicationTypeEnum.REGISTER_HF]: {
    orderedFields: [
      'hfAppealNum', // Bu maydon rasmda birinchi, lekin DTO da yo'q. Taxminan qo'shildi.
      'upperOrganization',
      'name', // XICHOdan foydalanuvchi tashkilotning nomi
      'tin',
      'activityType', // Bu DTO da bor, rasmda yo'q
      'legalAddress', // DTO da bor (XICHOdan foydalanuvchi tashkilotning pochta manzili rasmda)
      // 'name', // XICHOnomining nomi (takrorlanish)
      'regionId',
      'districtId',
      'address', // XICHOnomining manzili (XICHOning manzili)
      'location',
      'hfTypeId',
      'extraArea',
      'hazardousSubstance',
      'spheres',
      'phoneNumber',
      'email',
      // Fayllar
      'identificationCardPath',
      'receiptPath',
      'expertOpinionPath',
      'projectDocumentationPath',
      'cadastralPassportPath',
      'industrialSafetyDeclarationPath',
      'insurancePolicyPath',
      'licensePath',
      'permitPath',
      'certificationPath',
      'deviceTestingPath',
      'appointmentOrderPath',
      'ecologicalConclusionPath',
      'replyLetterPath',
    ],
    labels: {
      hfAppealNum: 'XICHO hisobga olish raqami', // Rasmda birinchi kelgan, DTO da yo'q
      upperOrganization: 'Yuqori turuvchi tashkilotning nomi (mavjud bo‘lsa)',
      name: 'XICHOning nomi', // Rasmda "XICHOdan foydalanuvchi tashkilotning nomi" va "XICHOnomining nomi"
      tin: 'Tashkilotning STIRi', // HfAppealDto dan, rasmda "Tashkilotning STIR"
      activityType: 'Faoliyat turi', // HfAppealDto dan
      legalAddress: 'Tashkilotning pochta manzili', // HfAppealDto dan, rasmda "XICHOdan foydalanuvchi tashkilotning pochta manzili"
      regionId: 'XICHO joylashgan viloyat',
      districtId: 'XICHO joylashgan tuman',
      address: 'XICHOning manzili', // Rasmda "XICHOnomining manzili"
      location: 'Geolokatsiya (X,Y)',
      hfTypeId: 'XICHOning turi',
      hfTypeName: 'XICHO turining nomi', // HfAppealDto dan (rasmda yo'q)
      extraArea: 'XICHO sexlari, uchastkalari, maydonchalari va boshqa ishlab chiqarish obʼektlarining nomi',
      hazardousSubstance: 'VMning 2008 yil 10 dekabrdagi 271-son qaroriga muvofiq xavfli moddalarning nomi va miqdori',
      spheres: 'Tarmoqlar',
      phoneNumber: 'Telefon raqami',
      email: 'Elektron pochta manzili',
      identificationCardPath: 'Identifikatsiya varag‘i fayli',
      receiptPath: 'XICHOni ro‘yxatga olish uchun to‘lov kvitansiyasi fayli',
      expertOpinionPath: 'Ekspertiza xulosasi fayli',
      projectDocumentationPath: 'Loyiha hujjatlari fayli',
      cadastralPassportPath: 'XICHO kadastr pasporti fayli',
      industrialSafetyDeclarationPath: 'Sanoat xavfsizligi deklaratsiyasi fayli',
      insurancePolicyPath: 'Sug‘urta polisi fayli',
      licensePath: 'Litsenziya fayli',
      permitPath: 'Ruxsatnoma fayli',
      certificationPath: 'XICHO xodimlarining sanoat xavfsizligi bo‘yicha attestatsiyadan o‘tganligi fayli',
      deviceTestingPath: 'Qurilmalarni sinovdan o‘tganligi fayli',
      appointmentOrderPath: 'Maʼsul xodim tayinlanganligi buyrug‘i fayli',
      ecologicalConclusionPath: 'Ekologiya qo‘mitasidan xulosasi fayli',
      replyLetterPath: 'Yong‘in xavfsizligi xulosasi fayli',
    },
  },
  [ApplicationTypeEnum.REGISTER_CRANE]: {
    orderedFields: [
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'model',
      'factory', // Ishlab chiqargan zavod nomi
      // 'ownerName', // Qurilma egasining nomi - DTO da 'factory' bilan bir xil bo'lishi mumkin
      'location',
      'manufacturedAt',
      'partialCheckDate',
      'fullCheckDate',
      'boomLength',
      'liftingCapacity',
      'regionId',
      'districtId',
      'address',
      'labelPath',
      'phoneNumber', // Umumiy maydonlardan
      'email', // Umumiy maydonlardan
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      hazardousFacilityId: 'XICHOʻ', // Rasmda "XICHO nomi"
      childEquipmentId: 'Kran turi',
      factoryNumber: 'Kranning zavod raqami',
      model: 'Model, marka',
      factory: 'Ishlab chiqargan zavod nomi',
      // ownerName: "Qurilma egasining nomi",
      location: 'Geolokatsiya (X,Y)',
      manufacturedAt: 'Ishlab chiqarilgan sana',
      partialCheckDate: 'Qisman texnik ko‘rik sanasi',
      fullCheckDate: 'To‘liq texnik ko‘rik sanasi',
      boomLength: 'Strelasining uzunligi (m)',
      liftingCapacity: 'Yuk koʻtara olish quvvati (tonna)',
      regionId: 'Kran joylashgan viloyat',
      districtId: 'Kran joylashgan tuman',
      address: 'Kran joylashgan manzil', // Rasmda "Kran joylashgan manzil", formda "Qurilma joylashgan manzil"
      labelPath: 'Kranning birkasi bilan surati',
    },
  },
  [ApplicationTypeEnum.REGISTER_BOILER]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'capacity',
      'environment',
      'pressure',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Qozon turi',
      factoryNumber: 'Qozonning zavod raqami',
      factory: 'Qozonni ishlab chiqargan zavod nomi',
      regionId: 'Qozon joylashgan viloyat',
      districtId: 'Qozon joylashgan tuman',
      address: 'Qozon joylashgan manzil',
      partialCheckDate: 'Tashqi va ichki ko‘rik sanasi',
      fullCheckDate: 'Gidrosinov o‘tkazish sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      capacity: 'Hajmi',
      environment: 'Muhit',
      pressure: 'Ruxsat etilgan bosim',
      labelPath: 'Qozonning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_ELEVATOR]: {
    // Lift uchun
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'sphere',
      'liftingCapacity',
      'stopCount',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Lift turi',
      factoryNumber: 'Liftning zavod raqami',
      factory: 'Liftni ishlab chiqargan zavod nomi',
      regionId: 'Lift joylashgan viloyat',
      districtId: 'Lift joylashgan tuman',
      address: 'Lift joylashgan manzil',
      partialCheckDate: 'Qisman texnik koʼrik sanasi',
      fullCheckDate: 'Toʼliq texnik koʼrik sanasi',
      sphere: 'Soha',
      liftingCapacity: 'Yuk koʻtara olish quvvati (kg)',
      stopCount: 'Toʼxtashlar soni',
      labelPath: 'Liftning birkasi bilan surʼati',
      additionalFilePath: 'Qoʻshimcha fayllar',
    },
  },
  [ApplicationTypeEnum.REGISTER_ESCALATOR]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'sphere',
      'passengersPerMinute',
      'length',
      'speed',
      'height',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Eskalator turi',
      factoryNumber: 'Eskalatorning zavod raqami',
      factory: 'Eskalatorni ishlab chiqargan zavod nomi',
      regionId: 'Eskalator joylashgan viloyat',
      districtId: 'Eskalator joylashgan tuman',
      address: 'Eskalator joylashgan manzil',
      partialCheckDate: 'Qisman texnik ko‘rik sanasi',
      fullCheckDate: 'To‘liq texnik ko‘rik sanasi',
      sphere: 'Soha',
      passengersPerMinute: 'O‘tkazish qobiliyati, kishi/soat',
      length: 'Uzunligi',
      speed: 'Tezligi',
      height: 'Ko‘tarish balandligi',
      labelPath: 'Eskalatorning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_CABLEWAY]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'speed',
      'passengerCount',
      'length',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Osma yo‘l turi',
      factoryNumber: 'Osma yo‘lning zavod raqami',
      factory: 'Osma yo‘l egasining nomi',
      regionId: 'Osma yo‘l joylashgan viloyat',
      districtId: 'Osma yo‘l joylashgan tuman',
      address: 'Osma yo‘lning joylashgan manzili',
      partialCheckDate: 'Qisman texnik ko‘rik sanasi',
      fullCheckDate: 'To‘liq texnik ko‘rik sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      speed: 'Harakat tezligi',
      passengerCount: 'Yo‘lovchilar soni',
      length: 'Uzunligi',
      labelPath: 'Osma yo‘lning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_HOIST]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'height',
      'liftingCapacity',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Yuk ko‘targich turi',
      factoryNumber: 'Yuk ko‘targichning zavod raqami',
      factory: 'Yuk ko‘targich egasining nomi',
      regionId: 'Yuk ko‘targich joylashgan viloyat',
      districtId: 'Yuk ko‘targich joylashgan tuman',
      address: 'Yuk ko‘targichning joylashgan manzili',
      partialCheckDate: 'Qisman texnik ko‘rik sanasi',
      fullCheckDate: 'To‘liq texnik ko‘rik sanasi',
      height: 'Ko‘tarish balandligi',
      liftingCapacity: 'Yuk ko‘tarish qobiliyati',
      labelPath: 'Yuk ko‘targichning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_PIPELINE]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'diameter',
      'thickness',
      'length',
      'pressure',
      'environment',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Quvur turi',
      factoryNumber: 'Quvurning zavod raqami',
      factory: 'Quvurni ishlab chiqargan zavod nomi',
      regionId: 'Quvur joylashgan viloyat',
      districtId: 'Quvur joylashgan tuman',
      address: 'Quvurning joylashgan manzili',
      partialCheckDate: 'Qisman texnik ko‘rik sanasi',
      fullCheckDate: 'To‘liq texnik ko‘rik sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      diameter: 'Diametr, mm',
      thickness: 'Devor qalinligi, mm',
      length: 'Uzunligi, m',
      pressure: 'Bosim, mPa',
      environment: 'Muhiti',
      labelPath: 'Quvurning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_CHEMICAL_CONTAINER]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'capacity',
      'environment',
      'pressure',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Idish (kimyo) turi',
      factoryNumber: 'Idishning zavod raqami',
      factory: 'Idishning egasining nomi',
      regionId: 'Idish joylashgan viloyat',
      districtId: 'Idish joylashgan tuman',
      address: 'Idish joylashgan manzil',
      partialCheckDate: 'Tashqi va ichki ko‘rik sanasi',
      fullCheckDate: 'Gidrosinov o‘tkazish sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      capacity: 'Hajmi',
      environment: 'Muhit',
      pressure: 'Ruxsat etilgan bosim',
      labelPath: 'Idishning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_HEAT_PIPELINE]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'diameter',
      'thickness',
      'length',
      'pressure',
      'temperature',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Bug‘ va issiq suv quvuri turi',
      factoryNumber: 'Quvurning zavod raqami',
      factory: 'Quvur egasining nomi',
      regionId: 'Quvur joylashgan viloyat',
      districtId: 'Quvur joylashgan tuman',
      address: 'Quvurning joylashgan manzili',
      partialCheckDate: 'Qisman texnik ko‘rik sanasi',
      fullCheckDate: 'To‘liq texnik ko‘rik sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      diameter: 'Diametr, mm',
      thickness: 'Devor qalinligi, mm',
      length: 'Uzunligi, m',
      pressure: 'Bosim, mPa',
      temperature: 'Harorat, °C',
      labelPath: 'Quvurning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_BOILER_UTILIZER]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'capacity',
      'environment',
      'pressure',
      'density',
      'temperature',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Qozon utilizator turi',
      factoryNumber: 'Qozon utilizatorining zavod raqami',
      factory: 'Qozon utilizatori egasining nomi',
      regionId: 'Qozon utilizatori joylashgan viloyat',
      districtId: 'Qozon utilizatori joylashgan tuman',
      address: 'Qozon utilizatorining joylashgan manzili',
      partialCheckDate: 'Tashqi va ichki ko‘rik sanasi',
      fullCheckDate: 'Gidrosinov o‘tkazish sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      capacity: 'Hajmi',
      environment: 'Muhit',
      pressure: 'Ruxsat etilgan bosim',
      density: 'Zichligi, kg/m³',
      temperature: 'Harorat, °C',
      labelPath: 'Qozon utilizatorining birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_LPG_CONTAINER]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'capacity',
      'environment',
      'pressure',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Idish (SUG) turi',
      factoryNumber: 'Idishning (SUG) zavod raqami',
      factory: 'Idishning (SUG) egasining nomi',
      regionId: 'Idish (SUG) joylashgan viloyat',
      districtId: 'Idish (SUG) joylashgan tuman',
      address: 'Idishning (SUG) joylashgan manzili',
      partialCheckDate: 'Tashqi va ichki ko‘rik sanasi',
      fullCheckDate: 'Gidrosinov o‘tkazish sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      capacity: 'Hajmi',
      environment: 'Muhit',
      pressure: 'Ruxsat etilgan bosim',
      labelPath: 'Idishning (SUG) birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_LPG_POWERED]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'capacity',
      'pressure',
      'fuel',
      'gasSupplyProjectPath',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Yiliga 100 ming va undan ortiq m³ tabiiy gazdan foydalanuvchi qurilma turi',
      factoryNumber: 'Qurilmaning zavod raqami',
      factory: 'Qurilma egasining nomi',
      regionId: 'Qurilma joylashgan viloyat',
      districtId: 'Qurilma joylashgan tuman',
      address: 'Qurilmaning joylashgan manzili',
      partialCheckDate: 'Tashqi va ichki ko‘rik sanasi',
      fullCheckDate: 'Gidrosinov o‘tkazish sanasi',
      capacity: 'Sarflash miqdori, m³/soat',
      pressure: 'Bosim, mPa',
      fuel: 'Yoqilg‘i turi',
      gasSupplyProjectPath: 'Gaz ta‘minoti loyihasi fayli',
      labelPath: 'Qurilmaning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_CONTAINER]: {
    orderedFields: [
      'phoneNumber',
      'hazardousFacilityId',
      'childEquipmentId',
      'factoryNumber',
      'factory',
      'model',
      'manufacturedAt',
      'regionId',
      'districtId',
      'address',
      'location',
      'partialCheckDate',
      'fullCheckDate',
      'nonDestructiveCheckDate',
      'capacity',
      'environment',
      'pressure',
      'labelPath',
      'saleContractPath',
      'equipmentCertPath',
      'assignmentDecreePath',
      'expertisePath',
      'installationCertPath',
      'additionalFilePath',
    ],
    labels: {
      ...commonEquipmentAppealLabels,
      childEquipmentId: 'Idish turi',
      factoryNumber: 'Idishning zavod raqami',
      factory: 'Idishni ishlab chiqargan zavod nomi',
      regionId: 'Idish joylashgan viloyat',
      districtId: 'Idish joylashgan tuman',
      address: 'Idish joylashgan manzil',
      partialCheckDate: 'Tashqi va ichki ko‘rik sanasi',
      fullCheckDate: 'Gidrosinov o‘tkazish sanasi',
      nonDestructiveCheckDate: 'Putur yetkazmaydigan nazoratdan o‘tkazish sanasi',
      capacity: 'Hajmi',
      environment: 'Muhit',
      pressure: 'Ruxsat etilgan bosim',
      labelPath: 'Idishning birkasi bilan sur‘ati',
    },
  },
  [ApplicationTypeEnum.REGISTER_IRS]: {
    orderedFields: [
      'phoneNumber',
      'email',
      'parentOrganization',
      'supervisorName',
      'supervisorPosition',
      'supervisorStatus',
      'supervisorEducation',
      'supervisorPhoneNumber',
      'division',
      'identifierType',
      'symbol',
      'sphere',
      'factoryNumber',
      'serialNumber',
      'activity',
      'type', // INM turi
      'category',
      'country',
      'manufacturedAt',
      'acceptedFrom',
      'acceptedAt',
      'isValid',
      'usageType',
      'storageLocation',
      'regionId',
      'districtId',
      'address',
      'passportPath',
      'additionalFilePath',
    ],
    labels: {
      phoneNumber: 'Ariza beruvchining telefon raqami',
      email: 'Elektron pochta',
      parentOrganization: 'Yuqori turuvchi tashkilot (mavjud bo‘lsa)',
      supervisorName: 'Rahbarning F.I.Sh.',
      supervisorPosition: 'Rahbarning lavozimi',
      supervisorStatus: 'Rahbarning radiatsiya xavfsizligi bo‘yicha tayyorgarlik holati',
      supervisorEducation: 'Rahbarning ma‘lumoti',
      supervisorPhoneNumber: 'Rahbarning telefon raqami',
      division: 'Bo‘linma nomi (INM bilan ishlovchi)',
      identifierType: 'INMning identifikatsiya raqami (SRM/NUM)',
      symbol: 'Radionuklid belgisi',
      sphere: 'Qo‘llash sohasi',
      factoryNumber: 'Zavod raqami',
      serialNumber: 'Seriya raqami',
      activity: 'Aktivligi, Bk',
      type: 'INM turi',
      category: 'INMlarning kategoriyasi',
      country: 'Ishlab chiqarilgan mamlakat',
      manufacturedAt: 'Ishlab chiqarilgan sana',
      acceptedFrom: 'Kimdan olinganligi',
      acceptedAt: 'Olingan sana',
      isValid: 'INM holati',
      usageType: 'INMdan foydalanish maqsadi',
      storageLocation: 'Saqlash joyi',
      passportPath: 'INM (qurilma) pasporti va sertifikati fayli',
      additionalFilePath: 'Qo‘shimcha maʼlumotlar',
      regionId: 'Joylashgan viloyat',
      districtId: 'Joylashgan tuman',
      address: 'Joylashgan manzil',
    },
  },
  // TODO: DEREGISTER_* va RE_REGISTER_* turlari uchun maydonlar va labellarni qo'shish kerak
  // Ularning DTO lari va formalarini ko'rib chiqish kerak
};

export default function getApplicationFields(appealType: ApplicationTypeEnum, fieldNames: string[]): FieldLabelPair[] {
  const mapping = appealLabelMappings[appealType];
  if (!mapping) {
    // Agar appealType uchun mapping topilmasa, har bir fieldName uchun default label qaytaramiz
    return fieldNames.map((fieldName) => ({ label: fieldName, value: fieldName }));
  }

  const result: FieldLabelPair[] = [];
  const foundFields = new Set<string>();

  // Birinchi navbatda orderedFields bo'yicha labellarni topamiz
  if (mapping.orderedFields) {
    for (const orderedFieldName of mapping.orderedFields) {
      if (fieldNames.includes(orderedFieldName)) {
        result.push({
          label: mapping.labels[orderedFieldName] || orderedFieldName,
          value: orderedFieldName,
        });
        foundFields.add(orderedFieldName);
      }
    }
  }

  // Keyin qolgan fieldNames uchun labellarni (tartibsiz) qo'shamiz
  for (const fieldName of fieldNames) {
    if (!foundFields.has(fieldName)) {
      result.push({
        label: mapping.labels[fieldName] || fieldName,
        value: fieldName,
      });
    }
  }

  return result;
}

// // Misol uchun chaqiruvlar:
// const hfFields: string[] = ['name', 'upperOrganization', 'regionId', 'hfTypeId', 'address'];
// const hfLabels: FieldLabelPair[] = getAppealFieldLabels(ApplicationTypeEnum.REGISTER_HF, hfFields);
// console.log('REGISTER_HF Labels:', hfLabels);
// /*
// Chiqishi kerak (tartib rasmga mos):
// [
//   { label: 'Yukori turuvchi tashkilotning nomi (mavjud bo‘lsa)', value: 'upperOrganization' },
//   { label: 'XICHOning nomi', value: 'name' },
//   { label: 'XICHO joylashgan viloyat', value: 'regionId' },
//   { label: 'XICHOning manzili', value: 'address' },
//   { label: 'XICHOning turi', value: 'hfTypeId' }
// ]
// */

// const craneFields: string[] = ['liftingCapacity', 'factoryNumber', 'boomLength', 'childEquipmentId'];
// const craneLabels: FieldLabelPair[] = getAppealFieldLabels(ApplicationTypeEnum.REGISTER_CRANE, craneFields);
// console.log('REGISTER_CRANE Labels:', craneLabels);
// /*
// Chiqishi kerak (tartib rasmga mos, keyin DTO):
// [
//   { label: 'Kran turi', value: 'childEquipmentId' },
//   { label: 'Kranning zavod raqami', value: 'factoryNumber' },
//   { label: 'Strelasining uzunligi (m)', value: 'boomLength' },
//   { label: 'Yuk koʻtara olish quvvati (tonna)', value: 'liftingCapacity' }
// ]
// */

// const irsFields: string[] = ['phoneNumber', 'supervisorName', 'activity', 'passportPath', 'unknownField'];
// const irsLabels: FieldLabelPair[] = getAppealFieldLabels(ApplicationTypeEnum.REGISTER_IRS, irsFields);
// console.log('REGISTER_IRS Labels:', irsLabels);
// /*
// Chiqishi kerak (tartib DTO ga mos, agar orderedFields da bo'lmasa):
// [
//   { label: 'Ariza beruvchining telefon raqami', value: 'phoneNumber' },
//   { label: 'Rahbarning F.I.Sh.', value: 'supervisorName' },
//   { label: 'Aktivligi, Bk', value: 'activity' },
//   { label: 'INM (qurilma) pasporti va sertifikati fayli', value: 'passportPath' },
//   { label: 'unknownField', value: 'unknownField' } // Label topilmagan holat
// ]
// */
