export enum MainApplicationCategory {
  REGISTER = 'REGISTER',
  UNREGISTER = 'UNREGISTER',
  REREGISTER = 'REREGISTER',
}

export enum ApplicationCategory {
  HF = 'HF',
  EQUIPMENTS = 'EQUIPMENTS',
  IRS = 'IRS',
  XRAY = 'XRAY',

  ILLEGAL_HF = 'ILLEGAL_HF',
  ILLEGAL_EQUIPMENTS = 'ILLEGAL_EQUIPMENTS',
  ILLEGAL_IRS = 'ILLEGAL_IRS',
  ILLEGAL_XRAY = 'ILLEGAL_XRAY',

  ACCREDITATION = 'ACCREDITATION',

  DEFAULT = 'DEFAULT',
}

export enum BuildingSphereType {
  RESIDENTIAL = 'RESIDENTIAL',
  HOTEL = 'HOTEL',
  SOCIAL = 'SOCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  SERVICE = 'SERVICE',
  OTHER = 'OTHER',
}

export enum ApplicationTypeEnum {
  REGISTER_HF = 'REGISTER_HF',
  DEREGISTER_HF = 'DEREGISTER_HF',
  RE_REGISTER_HF = 'RE_REGISTER_HF',
  RE_REGISTER_ILLEGAL_HF = 'RE_REGISTER_ILLEGAL_HF',

  REPORT_1 = 'REPORT_1',
  REPORT_2 = 'REPORT_2',
  REPORT_3 = 'REPORT_3',
  REPORT_4 = 'REPORT_4',
  REPORT_5 = 'REPORT_5',
  REPORT_6 = 'REPORT_6',
  REPORT_7 = 'REPORT_7',

  DEREGISTER_EQUIPMENT = 'DEREGISTER_EQUIPMENT',
  RE_REGISTER_EQUIPMENT = 'RE_REGISTER_EQUIPMENT',
  ILLEGAL_REGISTER_HF = 'ILLEGAL_REGISTER_HF',

  DEREGISTER_CRANE = 'DEREGISTER_CRANE',
  DEREGISTER_ELEVATOR = 'DEREGISTER_ELEVATOR',
  DEREGISTER_CONTAINER = 'DEREGISTER_CONTAINER',
  DEREGISTER_BOILER = 'DEREGISTER_BOILER',
  DEREGISTER_ESCALATOR = 'DEREGISTER_ESCALATOR',
  DEREGISTER_ATTRACTION = 'DEREGISTER_ATTRACTION',
  DEREGISTER_PIPELINE = 'DEREGISTER_PIPELINE',
  DEREGISTER_CHEMICAL_CONTAINER = 'DEREGISTER_CHEMICAL_CONTAINER',
  DEREGISTER_HEAT_PIPELINE = 'DEREGISTER_HEAT_PIPELINE',
  DEREGISTER_BOILER_UTILIZER = 'DEREGISTER_BOILER_UTILIZER',
  DEREGISTER_LPG_CONTAINER = 'DEREGISTER_LPG_CONTAINER',
  DEREGISTER_LPG_POWERED = 'DEREGISTER_LPG_POWERED',
  DEREGISTER_HOIST = 'DEREGISTER_HOIST',
  DEREGISTER_CABLEWAY = 'DEREGISTER_CABLEWAY',

  RE_REGISTER_CRANE = 'RE_REGISTER_CRANE',
  RE_REGISTER_ELEVATOR = 'RE_REGISTER_ELEVATOR',
  RE_REGISTER_CONTAINER = 'RE_REGISTER_CONTAINER',
  RE_REGISTER_BOILER = 'RE_REGISTER_BOILER',
  RE_REGISTER_ESCALATOR = 'RE_REGISTER_ESCALATOR',
  RE_REGISTER_ATTRACTION = 'RE_REGISTER_ATTRACTION',
  RE_REGISTER_PIPELINE = 'RE_REGISTER_PIPELINE',
  RE_REGISTER_CHEMICAL_CONTAINER = 'RE_REGISTER_CHEMICAL_CONTAINER',
  RE_REGISTER_HEAT_PIPELINE = 'RE_REGISTER_HEAT_PIPELINE',
  RE_REGISTER_BOILER_UTILIZER = 'RE_REGISTER_BOILER_UTILIZER',
  RE_REGISTER_LPG_CONTAINER = 'RE_REGISTER_LPG_CONTAINER',
  RE_REGISTER_LPG_POWERED = 'RE_REGISTER_LPG_POWERED',
  RE_REGISTER_HOIST = 'RE_REGISTER_HOIST',
  RE_REGISTER_CABLEWAY = 'RE_REGISTER_CABLEWAY',

  CRANE = 'CRANE',
  REGISTER_CRANE = 'REGISTER_CRANE',

  ELEVATOR = 'ELEVATOR',
  REGISTER_ELEVATOR = 'REGISTER_ELEVATOR',

  CONTAINER = 'CONTAINER',
  REGISTER_CONTAINER = 'REGISTER_CONTAINER',

  BOILER = 'BOILER',
  REGISTER_BOILER = 'REGISTER_BOILER',

  ESCALATOR = 'ESCALATOR',
  REGISTER_ESCALATOR = 'REGISTER_ESCALATOR',

  CABLEWAY = 'CABLEWAY',
  REGISTER_CABLEWAY = 'REGISTER_CABLEWAY',

  HOIST = 'HOIST',
  REGISTER_HOIST = 'REGISTER_HOIST',

  PIPELINE = 'PIPELINE',
  REGISTER_PIPELINE = 'REGISTER_PIPELINE',

  CHEMICAL_CONTAINER = 'CHEMICAL_CONTAINER',
  REGISTER_CHEMICAL_CONTAINER = 'REGISTER_CHEMICAL_CONTAINER',

  HEAT_PIPELINE = 'HEAT_PIPELINE',
  REGISTER_HEAT_PIPELINE = 'REGISTER_HEAT_PIPELINE',

  BOILER_UTILIZER = 'BOILER_UTILIZER',
  REGISTER_BOILER_UTILIZER = 'REGISTER_BOILER_UTILIZER',

  LPG_CONTAINER = 'LPG_CONTAINER',
  REGISTER_LPG_CONTAINER = 'REGISTER_LPG_CONTAINER',

  LPG_POWERED = 'LPG_POWERED',
  REGISTER_LPG_POWERED = 'REGISTER_LPG_POWERED',

  REGISTER_ATTRACTION_PASSPORT = 'REGISTER_ATTRACTION_PASSPORT',

  ATTRACTION = 'ATTRACTION',
  REGISTER_ATTRACTION = 'REGISTER_ATTRACTION',

  ACCREDIT_EXPERT = 'ACCREDIT_EXPERT',
  RE_ACCREDIT_EXPERT = 'RE_ACCREDIT_EXPERT',
  EXPEND_ACCREDITATION_SCOPE = 'EXPEND_ACCREDITATION_SCOPE',
  RE_ISSUE_ACCREDITATION_CERT = 'RE_ISSUE_ACCREDITATION_CERT',

  DEFAULT = 'DEFAULT',

  IRS = 'IRS',
  REGISTER_IRS = 'REGISTER_IRS',
  ACCEPT_IRS = 'ACCEPT_IRS',
  TRANSFER_IRS = 'TRANSFER_IRS',

  REGISTER_XRAY = 'REGISTER_XRAY',

  ILLEGAL_REGISTER_CRANE = 'ILLEGAL_REGISTER_CRANE',
  ILLEGAL_REGISTER_CONTAINER = 'ILLEGAL_REGISTER_CONTAINER',
  ILLEGAL_REGISTER_BOILER = 'ILLEGAL_REGISTER_BOILER',
  ILLEGAL_REGISTER_ESCALATOR = 'ILLEGAL_REGISTER_ESCALATOR',
  ILLEGAL_REGISTER_ATTRACTION = 'ILLEGAL_REGISTER_ATTRACTION',
  ILLEGAL_REGISTER_PIPELINE = 'ILLEGAL_REGISTER_PIPELINE',
  ILLEGAL_REGISTER_CHEMICAL_CONTAINER = 'ILLEGAL_REGISTER_CHEMICAL_CONTAINER',
  ILLEGAL_REGISTER_HEAT_PIPELINE = 'ILLEGAL_REGISTER_HEAT_PIPELINE',
  ILLEGAL_REGISTER_BOILER_UTILIZER = 'ILLEGAL_REGISTER_BOILER_UTILIZER',
  ILLEGAL_REGISTER_LPG_CONTAINER = 'ILLEGAL_REGISTER_LPG_CONTAINER',
  ILLEGAL_REGISTER_LPG_POWERED = 'ILLEGAL_REGISTER_LPG_POWERED',
  ILLEGAL_REGISTER_HOIST = 'ILLEGAL_REGISTER_HOIST',
  ILLEGAL_REGISTER_CABLEWAY = 'ILLEGAL_REGISTER_CABLEWAY',
  ILLEGAL_REGISTER_XRAY = 'ILLEGAL_REGISTER_XRAY',
  ILLEGAL_REGISTER_IRS = 'ILLEGAL_REGISTER_IRS',

  OIL_CONTAINER = 'OIL_CONTAINER',
  REGISTER_OIL_CONTAINER = 'REGISTER_OIL_CONTAINER',
  ILLEGAL_REGISTER_OIL_CONTAINER = 'ILLEGAL_REGISTER_OIL_CONTAINER',

  MODIFY_HF = 'MODIFY_HF',
  DEREGISTER_OIL_CONTAINER = 'DEREGISTER_OIL_CONTAINER',
  RE_REGISTER_OIL_CONTAINER = 'RE_REGISTER_OIL_CONTAINER',
  REGISTER_EXPERTISE_CONCLUSION = 'REGISTER_EXPERTISE_CONCLUSION',
  REGISTER_CADASTRE_PASSPORT = 'REGISTER_CADASTRE_PASSPORT',
  ATTESTATION_COMMITTEE = 'ATTESTATION_COMMITTEE',
  ATTESTATION_REGIONAL = 'ATTESTATION_REGIONAL',
  CHECK_DECLARATION = 'CHECK_DECLARATION',
}

export enum IrsIdentifierType {
  SRM = 'SRM',
  NUM = 'NUM',
}

export enum IrsCategory {
  I = 'I',
  II = 'II',
  III = 'III',
  IV = 'IV',
  V = 'V',
}

export enum stateService {
  X_RAY_PERMIT = 'Rentgen uskunasidan foydalanish uchun ruxsatnoma',
}

export enum IrsUsageType {
  USAGE = 'USAGE', // Ishlatish (foydalanish) uchun
  DISPOSAL = 'DISPOSAL', // Ko‘mish uchun
  EXPORT = 'EXPORT', // Chet-elga olib chiqish uchun
  STORAGE = 'TEMPORARY_STORAGE', // Vaqtinchalik saqlash uchun
}
