export enum MainApplicationCategory {
  REGISTER = 'REGISTER',
  UNREGISTER = 'UNREGISTER',
  REREGISTER = 'REREGISTER',
}

export enum ApplicationCategory {
  INM = 'INM',
  XRAY = 'XRAY',
  EQUIPMENTS = 'EQUIPMENTS',
  HF = 'HF',
  CADASTRE = 'CADASTRE',
  ACCREDITATION = 'ACCREDITATION',
  ATTESTATION_PREVENTION = 'ATTESTATION_PREVENTION',
  ILLEGAL = 'ILLEGAL',
  ILLEGAL_EQUIPMENTS = 'ILLEGAL_EQUIPMENTS',
  ILLEGAL_XRAY = 'ILLEGAL_XRAY',
  DEFAULT = 'DEFAULT',
}

export enum BuildingSphereType {
  RESIDENTIAL = 'RESIDENTIAL', // Turar joy binosi
  HOTEL = 'HOTEL', // Mehmonxona
  SOCIAL = 'SOCIAL', // Ijtimoiy soha
  INDUSTRIAL = 'INDUSTRIAL', // Sanoat korxonasi
  SERVICE = 'SERVICE', // Xizmat ko‘rsatish objekti
  OTHER = 'OTHER', // Boshqa objektlar
}

export enum ApplicationTypeEnum {
  REGISTER_HF = 'REGISTER_HF',
  DEREGISTER_HF = 'DEREGISTER_HF',
  MODIFY_HF = 'MODIFY_HF',

  REPORT_1 = 'REPORT_1',
  REPORT_2 = 'REPORT_2',
  REPORT_3 = 'REPORT_3',
  REPORT_4 = 'REPORT_4',

  DEREGISTER_EQUIPMENT = 'DEREGISTER_EQUIPMENT',
  RE_REGISTER_EQUIPMENT = 'RE_REGISTER_EQUIPMENT',
  ILLEGAL_REGISTER_HF = 'ILLEGAL_REGISTER_HF',

  DEREGISTER_CRANE = 'DEREGISTER_CRANE',
  DEREGISTER_CONTAINER = 'DEREGISTER_CONTAINER',
  DEREGISTER_BOILER = 'DEREGISTER_BOILER',
  DEREGISTER_ELEVATOR = 'DEREGISTER_ELEVATOR',
  DEREGISTER_ESCALATOR = 'DEREGISTER_ESCALATOR',
  DEREGISTER_ATTRACTION_PASSPORT = 'DEREGISTER_ATTRACTION_PASSPORT',
  DEREGISTER_ATTRACTION = 'DEREGISTER_ATTRACTION',
  DEREGISTER_PIPELINE = 'DEREGISTER_PIPELINE',
  DEREGISTER_CHEMICAL_CONTAINER = 'DEREGISTER_CHEMICAL_CONTAINER',
  DEREGISTER_HEAT_PIPELINE = 'DEREGISTER_HEAT_PIPELINE',
  DEREGISTER_BOILER_UTILIZER = 'DEREGISTER_BOILER_UTILIZER',
  DEREGISTER_LPG_CONTAINER = 'DEREGISTER_LPG_CONTAINER',
  DEREGISTER_LPG_POWERED = 'DEREGISTER_LPG_POWERED',
  DEREGISTER_HOIST = 'DEREGISTER_HOIST',
  DEREGISTER_CABLEWAY = 'DEREGISTER_CABLEWAY',

  RE_REGISTER_CRANE = 'RE_REGISTER_CRANE',
  RE_REGISTER_CONTAINER = 'RE_REGISTER_CONTAINER',
  RE_REGISTER_BOILER = 'RE_REGISTER_BOILER',
  RE_REGISTER_ELEVATOR = 'RE_REGISTER_ELEVATOR',
  RE_REGISTER_ESCALATOR = 'RE_REGISTER_ESCALATOR',
  RE_REGISTER_ATTRACTION_PASSPORT = 'RE_REGISTER_ATTRACTION_PASSPORT',
  RE_REGISTER_ATTRACTION = 'RE_REGISTER_ATTRACTION',
  RE_REGISTER_PIPELINE = 'RE_REGISTER_PIPELINE',
  RE_REGISTER_CHEMICAL_CONTAINER = 'RE_REGISTER_CHEMICAL_CONTAINER',
  RE_REGISTER_HEAT_PIPELINE = 'RE_REGISTER_HEAT_PIPELINE',
  RE_REGISTER_BOILER_UTILIZER = 'RE_REGISTER_BOILER_UTILIZER',
  RE_REGISTER_LPG_CONTAINER = 'RE_REGISTER_LPG_CONTAINER',
  RE_REGISTER_LPG_POWERED = 'RE_REGISTER_LPG_POWERED',
  RE_REGISTER_HOIST = 'RE_REGISTER_HOIST',
  RE_REGISTER_CABLEWAY = 'RE_REGISTER_CABLEWAY',

  CRANE = 'CRANE',
  REGISTER_CRANE = 'REGISTER_CRANE',

  CONTAINER = 'CONTAINER',
  REGISTER_CONTAINER = 'REGISTER_CONTAINER',

  BOILER = 'BOILER',
  REGISTER_BOILER = 'REGISTER_BOILER',

  ELEVATOR = 'ELEVATOR',
  REGISTER_ELEVATOR = 'REGISTER_ELEVATOR',

  ESCALATOR = 'ESCALATOR',
  REGISTER_ESCALATOR = 'REGISTER_ESCALATOR',

  CABLEWAY = 'CABLEWAY',
  REGISTER_CABLEWAY = 'REGISTER_CABLEWAY',

  HOIST = 'HOIST',
  REGISTER_HOIST = 'REGISTER_HOIST',

  PIPELINE = 'PIPELINE',
  REGISTER_PIPELINE = 'REGISTER_PIPELINE',

  CHEMICAL_CONTAINER = 'CHEMICAL_CONTAINER',
  REGISTER_CHEMICAL_CONTAINER = 'REGISTER_CHEMICAL_CONTAINER',

  HEAT_PIPELINE = 'HEAT_PIPELINE',
  REGISTER_HEAT_PIPELINE = 'REGISTER_HEAT_PIPELINE',

  BOILER_UTILIZER = 'BOILER_UTILIZER',
  REGISTER_BOILER_UTILIZER = 'REGISTER_BOILER_UTILIZER',

  LPG_CONTAINER = 'LPG_CONTAINER',
  REGISTER_LPG_CONTAINER = 'REGISTER_LPG_CONTAINER',

  LPG_POWERED = 'LPG_POWERED',
  REGISTER_LPG_POWERED = 'REGISTER_LPG_POWERED',

  ATTRACTION_PASSPORT = 'ATTRACTION_PASSPORT',
  REGISTER_ATTRACTION_PASSPORT = 'REGISTER_ATTRACTION_PASSPORT',

  ATTRACTION = 'ATTRACTION',
  REGISTER_ATTRACTION = 'REGISTER_ATTRACTION',

  REGISTER_ACCREDITATION = 'ACCREDIT_EXPERT_ORGANIZATION',
  RE_REGISTER_ACCREDITATION = 'RE_ACCREDIT_EXPERT_ORGANIZATION',
  EXPAND_ACCREDITATION = 'EXPEND_ACCREDITATION_SCOPE',
  REGISTER_EXPERTISE_CONCLUSION = 'REGISTER_EXPERTISE_CONCLUSION',

  REGISTER_CADASTRE_PASSPORT = 'REGISTER_CADASTRE_PASSPORT',
  REGISTER_DECLARATION = 'REGISTER_DECLARATION',

  REGISTER_ATTESTATION = 'REGISTER_ATTESTATION',
  ATTESTATION_COMMITTEE = 'ATTESTATION_COMMITTEE',
  ATTESTATION_REGIONAL = 'ATTESTATION_REGIONAL',

  DEFAULT = 'DEFAULT',

  IRS = 'IRS',
  REGISTER_IRS = 'REGISTER_IRS',
  ACCEPT_IRS = 'ACCEPT_IRS',
  TRANSFER_IRS = 'TRANSFER_IRS',

  REGISTER_XRAY = 'REGISTER_XRAY',

  ILLEGAL_REGISTER_CRANE = 'ILLEGAL_REGISTER_CRANE',
  ILLEGAL_REGISTER_CONTAINER = 'ILLEGAL_REGISTER_CONTAINER',
  ILLEGAL_REGISTER_BOILER = 'ILLEGAL_REGISTER_BOILER',
  ILLEGAL_REGISTER_ELEVATOR = 'ILLEGAL_REGISTER_ELEVATOR',
  ILLEGAL_REGISTER_ESCALATOR = 'ILLEGAL_REGISTER_ESCALATOR',
  ILLEGAL_REGISTER_ATTRACTION_PASSPORT = 'ILLEGAL_REGISTER_ATTRACTION_PASSPORT',
  ILLEGAL_REGISTER_PIPELINE = 'ILLEGAL_REGISTER_PIPELINE',
  ILLEGAL_REGISTER_CHEMICAL_CONTAINER = 'ILLEGAL_REGISTER_CHEMICAL_CONTAINER',
  ILLEGAL_REGISTER_HEAT_PIPELINE = 'ILLEGAL_REGISTER_HEAT_PIPELINE',
  ILLEGAL_REGISTER_BOILER_UTILIZER = 'ILLEGAL_REGISTER_BOILER_UTILIZER',
  ILLEGAL_REGISTER_LPG_CONTAINER = 'ILLEGAL_REGISTER_LPG_CONTAINER',
  ILLEGAL_REGISTER_LPG_POWERED = 'ILLEGAL_REGISTER_LPG_POWERED',
  ILLEGAL_REGISTER_HOIST = 'ILLEGAL_REGISTER_HOIST',
  ILLEGAL_REGISTER_CABLEWAY = 'ILLEGAL_REGISTER_CABLEWAY',
  ILLEGAL_REGISTER_XRAY = 'ILLEGAL_REGISTER_XRAY',
}

export enum IrsIdentifierType {
  SRM = 'SRM',
  NUM = 'NUM',
}

export enum IrsCategory {
  I = 'I',
  II = 'II',
  III = 'III',
  IV = 'IV',
  V = 'V',
}

export enum stateService {
  X_RAY_PERMIT = 'Rentgen uskunasidan foydalanish uchun ruxsatnoma',
}

export enum IrsUsageType {
  USAGE = 'USAGE', // Ishlatish (foydalanish) uchun
  DISPOSAL = 'DISPOSAL', // Ko‘mish uchun
  EXPORT = 'EXPORT', // Chet-elga olib chiqish uchun
  STORAGE = 'STORAGE', // Vaqtinchalik saqlash uchun
}
