export enum MainApplicationCategory {
  REGISTER = 'REGISTER',
  UNREGISTER = 'UNREGISTER',
  REREGISTER = 'REREGISTER',
}

export enum ApplicationCategory {
  INM = 'INM',
  HOKQ = 'HOKQ',
  XICHO = 'XICHO',
  CADASTRE = 'CADASTRE',
  ACCREDITATION = 'ACCREDITATION',
  ATTESTATION_PREVENTION = 'ATTESTATION_PREVENTION',
}

export enum BuildingSphereType {
  RESIDENTIAL = 'RESIDENTIAL', // Turar joy binosi
  HOTEL = 'HOTEL', // Mehmonxona
  SOCIAL = 'SOCIAL', // Ijtimoiy soha
  INDUSTRIAL = 'INDUSTRIAL', // Sanoat korxonasi
  SERVICE = 'SERVICE', // Xizmat ko‘rsatish objekti
  OTHER = 'OTHER', // Boshqa objektlar
}

export enum ApplicationTypeEnum {
  // Xavfli Ishlab Chiqarish Obyektini ro‘yxatga olish, o'zgartirish va chiqarish
  REGISTER_HF = 'REGISTER_HF',
  DEREGISTER_HF = 'DEREGISTER_HF',
  MODIFY_HF = 'MODIFY_HF',

  //Crane
  REGISTER_CRANE = 'REGISTER_CRANE',
  DEREGISTER_CRANE = 'DEREGISTER_CRANE',
  RE_REGISTER_CRANE = 'RE_REGISTER_CRANE',

  //Container - bosim ostida ishlovchi idish
  REGISTER_CONTAINER = 'REGISTER_CONTAINER',
  DEREGISTER_CONTAINER = 'DEREGISTER_CONTAINER',
  RE_REGISTER_CONTAINER = 'RE_REGISTER_CONTAINER',

  //Boiler - bug'qozon
  REGISTER_BOILER = 'REGISTER_BOILER',
  DEREGISTER_BOILER = 'DEREGISTER_BOILER',
  RE_REGISTER_BOILER = 'RE_REGISTER_BOILER',

  //Elevator - lift
  REGISTER_ELEVATOR = 'REGISTER_ELEVATOR',
  DEREGISTER_ELEVATOR = 'DEREGISTER_ELEVATOR',
  RE_REGISTER_ELEVATOR = 'RE_REGISTER_ELEVATOR',

  //Escalator
  REGISTER_ESCALATOR = 'REGISTER_ESCALATOR',
  DEREGISTER_ESCALATOR = 'DEREGISTER_ESCALATOR',
  RE_REGISTER_ESCALATOR = 'RE_REGISTER_ESCALATOR',

  //Cableway - osma qarqonli yuruvchi yo'l
  REGISTER_CABLEWAY = 'REGISTER_CABLEWAY',
  DEREGISTER_CABLEWAY = 'DEREGISTER_CABLEWAY',
  RE_REGISTER_CABLEWAY = 'RE_REGISTER_CABLEWAY',

  //hoist - yuk ko'targich
  REGISTER_HOIST = 'REGISTER_HOIST',
  DEREGISTER_HOIST = 'DEREGISTER_HOIST',
  RE_REGISTER_HOIST = 'RE_REGISTER_HOIST',

  //pipeline - quvur
  REGISTER_PIPELINE = 'REGISTER_PIPELINE',
  DEREGISTER_PIPELINE = 'DEREGISTER_PIPELINE',
  RE_REGISTER_PIPELINE = 'RE_REGISTER_PIPELINE',

  //Chemical container - bosim ostida ishlovchi idish (kimyoviy)
  REGISTER_CHEMICAL_CONTAINER = 'REGISTER_CHEMICAL_CONTAINER',
  DEREGISTER_CHEMICAL_CONTAINER = 'DEREGISTER_CHEMICAL_CONTAINER',
  RE_REGISTER_CHEMICAL_CONTAINER = 'RE_REGISTER_CHEMICAL_CONTAINER',

  //Heat pipe - bug' va issiqsuv quvuri
  REGISTER_HEAT_PIPELINE = 'REGISTER_HEAT_PIPELINE',
  DEREGISTER_HEAT_PIPELINE = 'DEREGISTER_HEAT_PIPELINE',
  RE_REGISTER_HEAT_PIPELINE = 'RE_REGISTER_HEAT_PIPELINE',

  //Boiler utilizer - qozon utilizator
  REGISTER_BOILER_UTILIZER = 'REGISTER_BOILER_UTILIZER',
  DEREGISTER_BOILER_UTILIZER = 'DEREGISTER_BOILER_UTILIZER',
  RE_REGISTER_BOILER_UTILIZER = 'RE_REGISTER_BOILER_UTILIZER',

  //LPG container (Liquefied Petroleum Gas) - bosim ostida ishlovchi idish (SUG)
  REGISTER_LPG_CONTAINER = 'REGISTER_LPG_CONTAINER',
  DEREGISTER_LPG_CONTAINER = 'DEREGISTER_LPG_CONTAINER',
  RE_REGISTER_LPG_CONTAINER = 'RE_REGISTER_LPG_CONTAINER',

  //LPG powered (Liquefied Petroleum Gas) - SUG bilan ishlovchi qurilmalar
  REGISTER_LPG_POWERED = 'REGISTER_LPG_POWERED',
  DEREGISTER_LPG_POWERED = 'DEREGISTER_LPG_POWERED',
  RE_REGISTER_LPG_POWERED = 'RE_REGISTER_LPG_POWERED',

  //attraction_passport - Attraksion pasporti
  REGISTER_ATTRACTION_PASSPORT = 'REGISTER_ATTRACTION_PASSPORT',
  DEREGISTER_ATTRACTION_PASSPORT = 'DEREGISTER_ATTRACTION_PASSPORT',
  RE_REGISTER_ATTRACTION_PASSPORT = 'RE_REGISTER_ATTRACTION_PASSPORT',

  //attraction - Attraksion
  REGISTER_ATTRACTION = 'REGISTER_ATTRACTION',
  DEREGISTER_ATTRACTION = 'DEREGISTER_ATTRACTION',
  RE_REGISTER_ATTRACTION = 'RE_REGISTER_ATTRACTION',

  DEFAULT = 'DEFAULT',

  //IRS (Ionizing Radiation Source ) - INM ro'yhatga olish, qabul qilib olish va berish
  REGISTER_IRS = 'REGISTER_IRS',
  ACCEPT_IRS = 'ACCEPT_IRS',
  TRANSFER_IRS = 'TRANSFER_IRS',
}
