import { AccreditationSphere } from '@/entities/accreditation/models/accreditation.enums'
import { SelectOption } from '@/shared/types'

export const ACCREDITATION_SPHERE_OPTIONS: (SelectOption<AccreditationSphere> & { point: string })[] = [
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1,
    name: "Xavfli ishlab chiqarish obyektlarini qurish, kengaytirish, qayta qurish, texnik jihatdan qayta jihozlash, konservatsiyalash va tugatishga doir loyiha hujjatlarini sanoat xavfsizligi ekspertizasidan o'tkazish",
    point: '1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1,
    name: "Ko'mir, kon, ruda va noruda sanoati obyektlari:",
    point: '1.1',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_1, name: 'Shaxta', point: '1.1.1' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_2,
    name: "Ko'mir va ruda konlari (erosti va erusti) obyektlari",
    point: '1.1.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_3,
    name: 'Boyituvchi, briketlovchi, aglomeratsiyalovchi fabrika va zavodlar',
    point: '1.1.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_4,
    name: "Boyitish-saralash va me'yorlash qurilmalari",
    point: '1.1.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_5,
    name: "Shlamto'plovchi gidrotexnik inshootlari, chiqindilarni saqlovchi, texnik suv havzalari obyektlari",
    point: '1.1.5',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_6,
    name: 'Oltin konlari va boshqa oltin saralash fabrikalari',
    point: '1.1.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_7,
    name: 'Oltin saralash fabrikasi va zavodlari (qurilmalari)',
    point: '1.1.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_8,
    name: 'Konlarni texnik rekultivatsiya qilish obyektlari',
    point: '1.1.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_9,
    name: "Foydali qazilma boyliklarini qazib olish bilan bog'liq bo'lmagan ishlab chiqarish obyektlari",
    point: '1.1.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_1_10,
    name: "Maxsus erosti, transport va umumiy xo'jalik inshootlarini qurish bilan bog'liq bo'lgan ishlab chiqarish obyektlari",
    point: '1.1.10',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_2, name: 'Neft va gaz sanoati obyektlari:', point: '1.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_1,
    name: 'Neft va gazga qazilgan parametrik, qidiruv, izlov, struktur va ekspluatatsion quduqlar hamda maxsus qazilgan quduqlar',
    point: '1.2.1',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_2, name: 'Erosti gaz omborlari', point: '1.2.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_3,
    name: 'Neft, gaz va gaz kondensati konlarini ishlatish va qurish; neft, gaz va gaz kondensatini qazib olish va tayyorlash obyektlari',
    point: '1.2.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_4,
    name: "Neftni, gazni va gaz kondensatini konlarda va konlar orasida tashish quvuro'tkazgichlari",
    point: '1.2.4',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_5, name: 'Magistral quvurlar', point: '1.2.5' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_6,
    name: 'Kompressor va nasos stansiyalari; gaz taqsimlash stansiyalari',
    point: '1.2.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_7,
    name: 'Qatlamdagi bosimni barqaror saqlab turish obyektlari',
    point: '1.2.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_8,
    name: 'Neft mahsulotlarini, neftni va gaz kondensatini saqlash va vaqtinchalik saqlash obyektlari',
    point: '1.2.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_2_9,
    name: "Avtomobillarga yoqilg'i quyish shoxobchalari",
    point: '1.2.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3,
    name: 'Kimyo, neft-kimyo, neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud kimyoviy xavfli ishlab chiqarish obyektlari:',
    point: '1.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_1,
    name: "Noorganik moddalar, ammiak, mineral o'g'itlar ishlab chiqarish obyektlari",
    point: '1.3.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_2,
    name: 'Neft va gazni qayta ishlash sanoati ishlab chiqarish va obyektlari',
    point: '1.3.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_3,
    name: 'Organik sintez ishlab chiqarish obyektlari',
    point: '1.3.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_4,
    name: "Sellyuloza qog'oz ishlab chiqarish obyektlari",
    point: '1.3.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_5,
    name: 'Kimyoviy tolalar, polimer materiallar, plastmassa hamda ulardan tayyorlanadigan mahsulotlarni ishlab chiqarish obyektlari',
    point: '1.3.5',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_6, name: 'Kriogen texnologiyalar obyektlari', point: '1.3.6' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_7, name: 'Ammiakli sovutish qurilmalari', point: '1.3.7' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_8,
    name: 'Elektroliz usulida vodorod va kislorod ishlab chiqarish obyektlari',
    point: '1.3.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_9,
    name: "Lok-bo'yoq mahsulotlari ishlab chiqarish obyektlari",
    point: '1.3.9',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_10, name: 'Spirt ishlab chiqarish obyektlari', point: '1.3.10' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_11,
    name: "Yog'-moy ishlab chiqarish obyektlari",
    point: '1.3.11',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_12,
    name: "Havoni parchalashda hosil bo'lgan mahsulotlarni olish va saqlash obyektlari",
    point: '1.3.12',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_13,
    name: 'Suvni xlor bilan qayta ishlash obyektlari',
    point: '1.3.13',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_3_14,
    name: "Portlash-yonish xavfi mavjud va kimyoviy xavfli mahsulotlarni (moddalarni) quyish, to'kish obyektlari",
    point: '1.3.14',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_4,
    name: "Bosimi 0,07 MPa yoki suvning isitish harorati 115º S dan yuqori bo'lgan jihosdan foydalaniladigan ishlab chiqarish obyektlari:",
    point: '1.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_4_1,
    name: "Bug' va suv isitish qozonlari (ishchi muhit turidan qat'i nazar)",
    point: '1.4.1',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_4_2, name: 'Bosim ostida ishlovchi idishlar', point: '1.4.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_4_3,
    name: "Bug' va issiq suv quvuro'tkazgichlar",
    point: '1.4.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_5,
    name: "Ko'chmas asosga o'rnatilgan yuk ko'tarish mexanizmlari, eskalatorlar, po'lat arqonli osma yo'llar, funikulyorlardan foydalaniladigan ishlab chiqarish obyektlari:",
    point: '1.5',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_5_1,
    name: "Yuk ko'tarish kranlari va mexanizmlari",
    point: '1.5.1',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_5_2, name: 'Eskalatorlar', point: '1.5.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_5_3,
    name: "Yuk va yo'lovchilar uchun osma po'lat arqonli yo'llar",
    point: '1.5.3',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_5_4, name: 'Funikulyorlar', point: '1.5.4' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_6,
    name: "Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta'minoti (gaz taqsimlash, gaz iste'moli) obyektlari:",
    point: '1.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_6_1,
    name: 'Suyultirilgan uglevodorod gazlarini saqlash va taqsimlash obyektlari',
    point: '1.6.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_6_2,
    name: "Avtomobillarga suyultirilgan uglevodorod gaz to'ldirish shoxobchalari",
    point: '1.6.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_6_3,
    name: "Avtomobillarga gaz to'ldirish kompressor shoxobchalari",
    point: '1.6.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_6_4,
    name: "Bosimi 12 kgf/sm² gacha bo'lgan gaz taqsimlash tizimlarining gaz tarmoqlari",
    point: '1.6.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_6_5,
    name: "Gaz iste'moli tizimlarining gaz tarmoqlari",
    point: '1.6.5',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_7, name: 'Metallurgiya sanoati obyektlari:', point: '1.7' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_7_1,
    name: "Qora metallar quyish sanoati, po'lat ishlab chiqarish obyektlari",
    point: '1.7.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_7_2,
    name: 'Rangli metallar quyish sanoati obyektlari',
    point: '1.7.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_8,
    name: "O'simlik xomashyosini saqlash va qayta ishlash obyektlari:",
    point: '1.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_1,
    name: "Qabul qilish, saqlash, quritish, qayta ishlash, alohida turuvchi qabul qilish va uzatish uskunasi, qabul qiluvchi-tozalash minorasi, alohida turuvchi don quritish uchastkalari, elevatorlar, silos tipidagi omborlar, qopsiz saqlash omborlari, solod ishlab chiqarish obyektlari, qayta ishlovchi va tayyorlovchi (maydalovchi) bo'limlar, shu jumladan oziq-ovqat sanoati korxonalari",
    point: '1.8.1',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_2, name: 'Un, yorma ishlab chiqarish obyektlari', point: '1.8.2' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_3, name: 'Omixta em ishlab chiqarish obyektlari', point: '1.8.3' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_4,
    name: 'Qopsiz qabul qilish, unni silos va bunkerlarda saqlash, non, makaron va qandolat mahsulotlarini ishlab chiqarish uchun unni tortish va elash obyektlari',
    point: '1.8.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_5,
    name: 'Un, yorma, non va makaron ishlab chiqarish korxonalari uchun qopli idishlarni tozalash va saralash obyektlari',
    point: '1.8.5',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_6, name: "Jo'xorini kalibrlovchi obyektlar", point: '1.8.6' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_7,
    name: "Urug'lik donlarni qayta ishlovchi obyektlar",
    point: '1.8.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_8_8,
    name: 'Tamaki mahsulotlarini tayyorlash obyektlari',
    point: '1.8.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_9,
    name: "Foydali qazilma konlarini qidirish va izlash bilan bog'liq geologiya-razvedka obyektlari (uglevodorod xomashyosi bo'lmagan)",
    point: '1.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_1_10,
    name: "Sanoatda qo'llaniladigan portlovchi moddalarni ishlab chiqarish, sinash va saqlash bilan bog'liq bo'lgan obyektlar",
    point: '1.10',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2,
    name: "Xavfli ishlab chiqarish obyektlarida qo'llaniladigan texnik qurilmalarni sanoat xavfsizligi ekspertizasidan o'tkazish",
    point: '2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1,
    name: "Ko'mir, kon, ruda va noruda sanoatidagi texnik qurilmalar:",
    point: '2.1',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_1, name: "Shaxtada qo'llaniladigan qurilmalar", point: '2.1.1' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_2,
    name: "Ko'mir va ruda konlari (erosti va erusti) obyektlarining qurilmalari",
    point: '2.1.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_3,
    name: 'Boyituvchi, briketlovchi, aglomeratsiyalovchi fabrika va zavodlarning qurilmalari',
    point: '2.1.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_4,
    name: "Boyitish-saralash va me'yorlash qurilmalari",
    point: '2.1.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_5,
    name: "Shlamto'plovchi gidrotexnik inshootlari, chiqindilarni saqlovchi va texnik suv havzalari obyektlarining qurilmalari",
    point: '2.1.5',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_6,
    name: 'Oltin konlari va boshqa oltin saralash fabrikalarining qurilmalari',
    point: '2.1.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_7,
    name: 'Oltin saralash fabrikasi va zavodlari qurilmalari',
    point: '2.1.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_8,
    name: 'Konlarni texnik rekultivatsiya qilish qurilmalari',
    point: '2.1.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_9,
    name: "Foydali qazilma boyliklari qazib olish bilan bog'liq bo'lmagan ishlab chiqarish obyektlarining qurilmalari",
    point: '2.1.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_1_10,
    name: "Maxsus erosti, transport va umumiy xo'jalik inshootlarini qurish bilan bog'liq bo'lgan ishlab chiqarish obyektlarining qurilmalari",
    point: '2.1.10',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2,
    name: 'Neft va gaz sanoatidagi texnik qurilmalar:',
    point: '2.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_1,
    name: "Quduqlarni burg'ulashda, ta'mirlashda va ishga tushirishda qo'llaniladigan qurilmalar",
    point: '2.2.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_2,
    name: "Neft va gaz quduqlarini ishlatishda qo'llaniladigan qurilmalar",
    point: '2.2.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_3,
    name: "Qatlamdagi bosimni va qatlamga hamda quduqqa ta'sir qiluvchi omillarni saqlashda qo'llaniladigan qurilmalar",
    point: '2.2.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_4,
    name: "Neft va gazni etkazib beruvchi stansiyalarda qo'llaniladigan qurilmalar",
    point: '2.2.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_5,
    name: "Magistral quvurlar tizimini qurishda, ishlatishda va ta'mirlashda qo'llaniladigan qurilmalar",
    point: '2.2.5',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_6,
    name: 'Gaz va neft mahsulotlari quvurlari; kon va konlararo quvurlar',
    point: '2.2.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_7,
    name: "Kompozit va po'lat quvurlar qismlari va quvurlari, shu jumladan tiqin (zapor), me'yorlovchi va himoyalovchi armaturalar qismlari",
    point: '2.2.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_8,
    name: 'Neft, kondensat va neft mahsulotlari uchun rezervuarlar va ularning qurilmalari',
    point: '2.2.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_9,
    name: 'Kompressor, nasos va gaz taqsimlash stansiyalari qurilmalari',
    point: '2.2.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_2_10,
    name: "Neft va gazni yig'ish va tayyorlash qurilmalari",
    point: '2.2.10',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3,
    name: 'Kimyo, neft-kimyo, neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud va kimyoviy xavfli ishlab chiqarish obyektlaridagi texnik qurilmalar:',
    point: '2.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_1,
    name: "Noorganik moddalar, ammiak, mineral o'g'itlar ishlab chiqarish obyektlarining qurilmalari",
    point: '2.3.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_2,
    name: 'Neft va gazni qayta ishlash obyektlarining qurilmalari',
    point: '2.3.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_3,
    name: 'Organik sintez ishlab chiqarish obyektlarining qurilmalari',
    point: '2.3.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_4,
    name: "Sellyuloza qog'oz ishlab chiqarish obyektlarining qurilmalari",
    point: '2.3.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_5,
    name: 'Kimyoviy tolalar, polimer materiallar, plastmassa hamda ulardan tayyorlanadigan mahsulotlar ishlab chiqarish obyektlarining qurilmalari',
    point: '2.3.5',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_6, name: 'Kriogen texnologiyasi qurilmalari', point: '2.3.6' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_7, name: 'Ammiakli sovutish qurilmalari', point: '2.3.7' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_8,
    name: 'Elektroliz usulida vodorod va kislorod ishlab chiqarish obyektlarining qurilmalari',
    point: '2.3.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_9,
    name: "Lok-bo'yoq mahsulotlari ishlab chiqarish obyektlarining qurilmalari",
    point: '2.3.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_10,
    name: 'Spirt ishlab chiqarish obyektlarining qurilmalari',
    point: '2.3.10',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_11,
    name: "Yog'-moy ishlab chiqarish obyektlarining qurilmalari",
    point: '2.3.11',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_12,
    name: "Havoni parchalashda hosil bo'lgan mahsulotlarni olish va saqlash obyektlarining qurilmalari",
    point: '2.3.12',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_13,
    name: 'Suvni xlor bilan qayta ishlash obyektlarining qurilmalari',
    point: '2.3.13',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_3_14,
    name: "Portlash-yonish xavfi mavjud va kimyoviy xavfli mahsulotlarni (moddalarni) quyish, to'kish obyektlarining qurilmalari",
    point: '2.3.14',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_4,
    name: "Bosimi 0,07 MPa dan yuqori bo'lgan yoki suvning harorati 115º S dan yuqori bo'lgan sharoitda ishlaydigan texnik qurilmalar:",
    point: '2.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_4_1,
    name: "Suv isitish va bug' qozonlari hamda ularning qurilmalari",
    point: '2.4.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_4_2,
    name: "Bosim 0,07 MPa dan yuqori bo'lgan bosim ostida ishlovchi idishlar",
    point: '2.4.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_4_3,
    name: "Bosim 0,07 MPa dan va suvning harorati 115 º S dan yuqori bo'lgan bug' va issiq suv quvurlari",
    point: '2.4.3',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_4_4, name: "Avtonom bug'qizdirgichlar", point: '2.4.4' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_4_5, name: 'Avtonom ekonomayzerlar', point: '2.4.5' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_5,
    name: "Ko'chmas asosga o'rnatilgan yuk ko'tarish mexanizmlari, eskalatorlar, po'lat arqonli osma yo'llar, funikulyorlar:",
    point: '2.5',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_1, name: "Yuk ko'tarish kranlari", point: '2.5.1' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_2, name: 'Kran-manipulyatorlar', point: '2.5.2' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_3, name: 'Quvuryotqizgich kranlar', point: '2.5.3' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_4, name: "Ko'targichlar (vishkalar)", point: '2.5.4' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_5, name: "Qurilish ko'targichlari", point: '2.5.5' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_6, name: 'Liftlar', point: '2.5.6' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_7,
    name: "Nogironligi bo'lgan shaxslarni ko'tarishga mo'ljallangan platformalar",
    point: '2.5.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_8,
    name: "Yuk va yo'lovchilar uchun osma po'lat arqonli yo'llar",
    point: '2.5.8',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_9, name: 'Funikulyorlar', point: '2.5.9' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_10, name: 'Eskalatorlar', point: '2.5.10' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_5_11,
    name: "Yuk ko'tarish mexanizmlari va idishlar (metallurgiyadan tashqari)",
    point: '2.5.11',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_6,
    name: "Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta'minoti (gaz taqsimlash, gaz iste'moli) obyektlarining texnik qurilmalari:",
    point: '2.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_6_1,
    name: 'Suyultirilgan uglevodorod gazlarini saqlash va taqsimlash obyektlarining qurilmalari',
    point: '2.6.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_6_2,
    name: "Avtomobillarga suyultirilgan uglevodorod gaz to'ldirish shoxobchalarining qurilmalari",
    point: '2.6.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_6_3,
    name: "Avtomobillarga gaz to'ldirish kompressor shoxobchalarining qurilmalari",
    point: '2.6.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_6_4,
    name: "Bosimi 12 kgf/sm² gacha bo'lgan gaz taqsimlash tizimlari",
    point: '2.6.4',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_6_5, name: "Gaz iste'moli tizimlari", point: '2.6.5' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_7, name: 'Metallurgiya sanoati texnik qurilmalari', point: '2.7' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_7_1,
    name: "Qora metallar quyish, po'lat ishlab chiqarish obyektlarining qurilmalari",
    point: '2.7.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_7_2,
    name: 'Rangli metallar quyish sanoati obyektlarining qurilmalari',
    point: '2.7.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8,
    name: "O'simlik xomashyosini saqlash va qayta ishlash obyektlarining texnik qurilmalari:",
    point: '2.8',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_1, name: 'Elevator ombori qurilmalari', point: '2.8.1' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_2,
    name: 'Un ishlab chiqarish korxonalari qurilmalari',
    point: '2.8.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_3,
    name: 'Yorma ishlab chiqarish obyektlarining qurilmalari',
    point: '2.8.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_4,
    name: 'Omixta em ishlab chiqarish obyektlarining qurilmalari',
    point: '2.8.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_5,
    name: 'Qopsiz qabul qilish, unni silos va bunkerlarda saqlash, non, makaron va qandolat mahsulotlarini ishlab chiqarish uchun unni tortish va elash obyektlarining qurilmalari',
    point: '2.8.5',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_6,
    name: "O'simlik xomashyosini qabul qilish, saqlash, quritish, qayta ishlash, alohida turuvchi qabul qilish va uzatish uskunasi, qabul qiluvchi tozalash minorasi, alohida turuvchi don quritish uchastkalari, elevatorlar, silos tipidagi omborlar, qopsiz saqlash omborlari, solod ishlab chiqarish obyektlari, qayta ishlovchi va tayyorlovchi (maydalovchi) bo'limlar, shu jumladan oziq-ovqat sanoati korxonalari qurilmalari",
    point: '2.8.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_7,
    name: "Jo'xorini kalibrlovchi ishlab chiqarish obyektlarining qurilmalari",
    point: '2.8.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_8,
    name: "Urug'lik donlarni qayta ishlaydigan obyektlarining qurilmalari",
    point: '2.8.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_8_9,
    name: 'Tamaki tayyorlash liniyalari obyektlarining qurilmalari',
    point: '2.8.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_9,
    name: "Foydali qazilma konlarini qidirish va izlash bilan bog'liq geologiya-razvedka obyektlaridagi texnik qurilmalar (uglevodorod xomashyosi bo'lmagan)",
    point: '2.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_2_10,
    name: "Sanoatga mo'ljallangan portlovchi moddalarni ishlab chiqarish, sinash va saqlashda qo'llaniladigan texnik qurilmalar",
    point: '2.10',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3,
    name: "Xavfli ishlab chiqarish obyektidagi binolar va inshootlarni sanoat xavfsizligi ekspertizasidan o'tkazish",
    point: '3',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_3_1, name: "Ko'mir, kon-ruda va noruda sanoatlarida:", point: '3.1' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_3_1_1, name: 'Erusti kompleks bino va inshootlar', point: '3.1.1' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_3_1_2, name: 'Erosti inshootlari', point: '3.1.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_1_3,
    name: "Foydali qazilma boyliklarini qazib olish bilan bog'liq bo'lmagan ishlab chiqarish obyektlaridagi bino va inshootlar",
    point: '3.1.3',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_3_2, name: 'Neft va gaz sanoati obyektlarida:', point: '3.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_2_1,
    name: "Quduqlarni qazish va ta'mirlash bilan bog'liq bo'lgan obyektlardagi bino va inshootlar",
    point: '3.2.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_2_2,
    name: 'Neft va gaz qazib olish va ularni tayyorlash obyektlaridagi bino va inshootlar',
    point: '3.2.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_2_3,
    name: 'Magistral quvurlar obyektlaridagi bino va inshootlar',
    point: '3.2.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_2_4,
    name: 'Neft mahsulotlarini, kondensat va neftni saqlash va uzatish obyektlaridagi bino va inshootlar',
    point: '3.2.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_3,
    name: 'Kimyo, neft-kimyo va neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud kimyoviy xavfli ishlab chiqarish obyektlaridagi bino va inshootlar',
    point: '3.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_4,
    name: "Bosimi 0,07 MPa dan yuqori bo'lgan yoki suvning isish harorati 115º S dan yuqori bo'lgan qurilmalar joylashgan bino va inshootlar",
    point: '3.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_5,
    name: "Ko'chmas asosga o'rnatilgan yuk ko'tarish mexanizmlari, eskalatorlar, po'lat arqonli osma yo'llar, funikulyorlardan foydalaniladigan ishlab chiqarish obyektlaridagi bino va inshootlar",
    point: '3.5',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_6,
    name: "Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta'minoti (gaz taqsimlash, gaz iste'moli) obyektlaridagi bino va inshootlar:",
    point: '3.6',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_6_1,
    name: "Gaz jihozlari o'rnatilgan bino va inshootlar (qozonxonalar, sexlar)",
    point: '3.6.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_6_2,
    name: "Avtomobillarga gaz (suyultirilgan uglevodorod gaz) to'ldirish shoxobchalarining bino va inshootlari",
    point: '3.6.2',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_7,
    name: 'Metallurgiya sanoati obyektlaridagi bino va inshootlar',
    point: '3.7',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_8,
    name: "O'simlik xomashyosini saqlash va qayta ishlash obyektlaridagi bino va inshootlar",
    point: '3.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_9,
    name: "Foydali qazilma konlarini qidirish va izlash bilan bog'liq geologiya-razvedka obyektlaridagi (uglevodorod xomashyosi bo'lmagan) bino va inshootlar",
    point: '3.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_3_10,
    name: "Sanoatda qo'llaniladigan portlovchi moddalarni ishlab chiqarish, sinash va saqlash bilan bog'liq bo'lgan obyektlardagi bino va inshootlar",
    point: '3.10',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4,
    name: "Sanoat xavfsizligi deklaratsiyasi va xavfli ishlab chiqarish obyektlaridan foydalanish bilan bog'liq boshqa hujjatlarni sanoat xavfsizligi ekspertizasidan o'tkazish",
    point: '4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_1,
    name: "Ko'mir, kon, ruda va noruda sanoati obyektlari:",
    point: '4.1',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_4_1_1, name: 'Erusti ishlab chiqarish obyektlari', point: '4.1.1' },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_4_1_2, name: 'Erosti ishlab chiqarish obyektlari', point: '4.1.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_1_3,
    name: "Foydali qazilma boyliklarini qazib olish bilan bog'liq bo'lmagan ishlab chiqarish obyektlari",
    point: '4.1.3',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_4_2, name: 'Neft va gaz sanoati obyektlari:', point: '4.2' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_2_1,
    name: "Quduqlarni qazish va ta'mirlash bilan bog'liq bo'lgan obyektlar",
    point: '4.2.1',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_2_2,
    name: 'Neft va gaz qazib olish va ularni tayyorlash obyektlari',
    point: '4.2.2',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_4_2_3, name: 'Magistral quvurlar obyektlari', point: '4.2.3' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_2_4,
    name: 'Neft mahsulotlarini, kondensat va neftni saqlash va uzatish obyektlari',
    point: '4.2.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_3,
    name: 'Kimyo, neft-kimyo, neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud kimyoviy xavfli ishlab chiqarish obyektlari',
    point: '4.3',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_4,
    name: "Bosimi 0,07 MPa dan yuqori yoki suvning harorati 115ºS dan yuqori bo'lgan qurilmalardan foydalaniladigan ishlab chiqarish obyektlari",
    point: '4.4',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_5,
    name: "Ko'chmas asosga o'rnatilgan yuk ko'tarish mexanizmlari, eskalatorlar, po'lat arqonli osma yo'llar, funikulyorlardan foydalaniladigan ishlab chiqarish obyektlari",
    point: '4.5',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_6,
    name: "Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta'minoti (gaz taqsimlash, gaz iste'moli) obyektlari",
    point: '4.6',
  },
  { id: AccreditationSphere.ACCREDITATION_SPHERE_4_7, name: 'Metallurgiya sanoati obyektlari', point: '4.7' },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_8,
    name: "O'simlik xomashyosini saqlash va qayta ishlash obyektlari",
    point: '4.8',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_9,
    name: "Foydali qazilma konlarini qidirish va izlash bilan bog'liq geologiya-razvedka obyektlari (uglevodorod xomashyosi bo'lmagan)",
    point: '4.9',
  },
  {
    id: AccreditationSphere.ACCREDITATION_SPHERE_4_10,
    name: "Sanoatda qo'llaniladigan portlovchi moddalarni ishlab chiqarish, sinash va saqlash bilan bog'liq bo'lgan obyektlar",
    point: '4.10',
  },
]
