export enum AccreditationSphere {
  SPHERE_1 = 'SPHERE_1',
  SPHERE_1_1 = 'SPHERE_1_1',
  SPHERE_1_1_1 = 'SPHERE_1_1_1',
  SPHERE_1_1_2 = 'SPHERE_1_1_2',
  SPHERE_1_1_3 = 'SPHERE_1_1_3',
  SPHERE_1_1_4 = 'SPHERE_1_1_4',
  SPHERE_1_1_5 = 'SPHERE_1_1_5',
  SPHERE_1_1_6 = 'SPHERE_1_1_6',
  SPHERE_1_1_7 = 'SPHERE_1_1_7',
  SPHERE_1_1_8 = 'SPHERE_1_1_8',
  SPHERE_1_1_9 = 'SPHERE_1_1_9',
  SPHERE_1_1_10 = 'SPHERE_1_1_10',
  SPHERE_1_2 = 'SPHERE_1_2',
  SPHERE_1_2_1 = 'SPHERE_1_2_1',
  SPHERE_1_2_2 = 'SPHERE_1_2_2',
  SPHERE_1_2_3 = 'SPHERE_1_2_3',
  SPHERE_1_2_4 = 'SPHERE_1_2_4',
  SPHERE_1_2_5 = 'SPHERE_1_2_5',
  SPHERE_1_2_6 = 'SPHERE_1_2_6',
  SPHERE_1_2_7 = 'SPHERE_1_2_7',
  SPHERE_1_2_8 = 'SPHERE_1_2_8',
  SPHERE_1_2_9 = 'SPHERE_1_2_9',
  SPHERE_1_3 = 'SPHERE_1_3',
  SPHERE_1_3_1 = 'SPHERE_1_3_1',
  SPHERE_1_3_2 = 'SPHERE_1_3_2',
  SPHERE_1_3_3 = 'SPHERE_1_3_3',
  SPHERE_1_3_4 = 'SPHERE_1_3_4',
  SPHERE_1_3_5 = 'SPHERE_1_3_5',
  SPHERE_1_3_6 = 'SPHERE_1_3_6',
  SPHERE_1_3_7 = 'SPHERE_1_3_7',
  SPHERE_1_3_8 = 'SPHERE_1_3_8',
  SPHERE_1_3_9 = 'SPHERE_1_3_9',
  SPHERE_1_3_10 = 'SPHERE_1_3_10',
  SPHERE_1_3_11 = 'SPHERE_1_3_11',
  SPHERE_1_3_12 = 'SPHERE_1_3_12',
  SPHERE_1_3_13 = 'SPHERE_1_3_13',
  SPHERE_1_3_14 = 'SPHERE_1_3_14',
  SPHERE_1_4 = 'SPHERE_1_4',
  SPHERE_1_4_1 = 'SPHERE_1_4_1',
  SPHERE_1_4_2 = 'SPHERE_1_4_2',
  SPHERE_1_4_3 = 'SPHERE_1_4_3',
  SPHERE_1_5 = 'SPHERE_1_5',
  SPHERE_1_5_1 = 'SPHERE_1_5_1',
  SPHERE_1_5_2 = 'SPHERE_1_5_2',
  SPHERE_1_5_3 = 'SPHERE_1_5_3',
  SPHERE_1_5_4 = 'SPHERE_1_5_4',
  SPHERE_1_6 = 'SPHERE_1_6',
  SPHERE_1_6_1 = 'SPHERE_1_6_1',
  SPHERE_1_6_2 = 'SPHERE_1_6_2',
  SPHERE_1_6_3 = 'SPHERE_1_6_3',
  SPHERE_1_6_4 = 'SPHERE_1_6_4',
  SPHERE_1_6_5 = 'SPHERE_1_6_5',
  SPHERE_1_7 = 'SPHERE_1_7',
  SPHERE_1_7_1 = 'SPHERE_1_7_1',
  SPHERE_1_7_2 = 'SPHERE_1_7_2',
  SPHERE_1_8 = 'SPHERE_1_8',
  SPHERE_1_8_1 = 'SPHERE_1_8_1',
  SPHERE_1_8_2 = 'SPHERE_1_8_2',
  SPHERE_1_8_3 = 'SPHERE_1_8_3',
  SPHERE_1_8_4 = 'SPHERE_1_8_4',
  SPHERE_1_8_5 = 'SPHERE_1_8_5',
  SPHERE_1_8_6 = 'SPHERE_1_8_6',
  SPHERE_1_8_7 = 'SPHERE_1_8_7',
  SPHERE_1_8_8 = 'SPHERE_1_8_8',
  SPHERE_1_9 = 'SPHERE_1_9',
  SPHERE_1_10 = 'SPHERE_1_10',
  SPHERE_2 = 'SPHERE_2',
  SPHERE_2_1 = 'SPHERE_2_1',
  SPHERE_2_1_1 = 'SPHERE_2_1_1',
  SPHERE_2_1_2 = 'SPHERE_2_1_2',
  SPHERE_2_1_3 = 'SPHERE_2_1_3',
  SPHERE_2_1_4 = 'SPHERE_2_1_4',
  SPHERE_2_1_5 = 'SPHERE_2_1_5',
  SPHERE_2_1_6 = 'SPHERE_2_1_6',
  SPHERE_2_1_7 = 'SPHERE_2_1_7',
  SPHERE_2_1_8 = 'SPHERE_2_1_8',
  SPHERE_2_1_9 = 'SPHERE_2_1_9',
  SPHERE_2_1_10 = 'SPHERE_2_1_10',
  SPHERE_2_2 = 'SPHERE_2_2',
  SPHERE_2_2_1 = 'SPHERE_2_2_1',
  SPHERE_2_2_2 = 'SPHERE_2_2_2',
  SPHERE_2_2_3 = 'SPHERE_2_2_3',
  SPHERE_2_2_4 = 'SPHERE_2_2_4',
  SPHERE_2_2_5 = 'SPHERE_2_2_5',
  SPHERE_2_2_6 = 'SPHERE_2_2_6',
  SPHERE_2_2_7 = 'SPHERE_2_2_7',
  SPHERE_2_2_8 = 'SPHERE_2_2_8',
  SPHERE_2_2_9 = 'SPHERE_2_2_9',
  SPHERE_2_2_10 = 'SPHERE_2_2_10',
  SPHERE_2_3 = 'SPHERE_2_3',
  SPHERE_2_3_1 = 'SPHERE_2_3_1',
  SPHERE_2_3_2 = 'SPHERE_2_3_2',
  SPHERE_2_3_3 = 'SPHERE_2_3_3',
  SPHERE_2_3_4 = 'SPHERE_2_3_4',
  SPHERE_2_3_5 = 'SPHERE_2_3_5',
  SPHERE_2_3_6 = 'SPHERE_2_3_6',
  SPHERE_2_3_7 = 'SPHERE_2_3_7',
  SPHERE_2_3_8 = 'SPHERE_2_3_8',
  SPHERE_2_3_9 = 'SPHERE_2_3_9',
  SPHERE_2_3_10 = 'SPHERE_2_3_10',
  SPHERE_2_3_11 = 'SPHERE_2_3_11',
  SPHERE_2_3_12 = 'SPHERE_2_3_12',
  SPHERE_2_3_13 = 'SPHERE_2_3_13',
  SPHERE_2_3_14 = 'SPHERE_2_3_14',
  SPHERE_2_4 = 'SPHERE_2_4',
  SPHERE_2_4_1 = 'SPHERE_2_4_1',
  SPHERE_2_4_2 = 'SPHERE_2_4_2',
  SPHERE_2_4_3 = 'SPHERE_2_4_3',
  SPHERE_2_4_4 = 'SPHERE_2_4_4',
  SPHERE_2_4_5 = 'SPHERE_2_4_5',
  SPHERE_2_5 = 'SPHERE_2_5',
  SPHERE_2_5_1 = 'SPHERE_2_5_1',
  SPHERE_2_5_2 = 'SPHERE_2_5_2',
  SPHERE_2_5_3 = 'SPHERE_2_5_3',
  SPHERE_2_5_4 = 'SPHERE_2_5_4',
  SPHERE_2_5_5 = 'SPHERE_2_5_5',
  SPHERE_2_5_6 = 'SPHERE_2_5_6',
  SPHERE_2_5_7 = 'SPHERE_2_5_7',
  SPHERE_2_5_8 = 'SPHERE_2_5_8',
  SPHERE_2_5_9 = 'SPHERE_2_5_9',
  SPHERE_2_5_10 = 'SPHERE_2_5_10',
  SPHERE_2_5_11 = 'SPHERE_2_5_11',
  SPHERE_2_6 = 'SPHERE_2_6',
  SPHERE_2_6_1 = 'SPHERE_2_6_1',
  SPHERE_2_6_2 = 'SPHERE_2_6_2',
  SPHERE_2_6_3 = 'SPHERE_2_6_3',
  SPHERE_2_6_4 = 'SPHERE_2_6_4',
  SPHERE_2_6_5 = 'SPHERE_2_6_5',
  SPHERE_2_7 = 'SPHERE_2_7',
  SPHERE_2_7_1 = 'SPHERE_2_7_1',
  SPHERE_2_7_2 = 'SPHERE_2_7_2',
  SPHERE_2_8 = 'SPHERE_2_8',
  SPHERE_2_8_1 = 'SPHERE_2_8_1',
  SPHERE_2_8_2 = 'SPHERE_2_8_2',
  SPHERE_2_8_3 = 'SPHERE_2_8_3',
  SPHERE_2_8_4 = 'SPHERE_2_8_4',
  SPHERE_2_8_5 = 'SPHERE_2_8_5',
  SPHERE_2_8_6 = 'SPHERE_2_8_6',
  SPHERE_2_8_7 = 'SPHERE_2_8_7',
  SPHERE_2_8_8 = 'SPHERE_2_8_8',
  SPHERE_2_8_9 = 'SPHERE_2_8_9',
  SPHERE_2_9 = 'SPHERE_2_9',
  SPHERE_2_10 = 'SPHERE_2_10',
  SPHERE_3 = 'SPHERE_3',
  SPHERE_3_1 = 'SPHERE_3_1',
  SPHERE_3_1_1 = 'SPHERE_3_1_1',
  SPHERE_3_1_2 = 'SPHERE_3_1_2',
  SPHERE_3_1_3 = 'SPHERE_3_1_3',
  SPHERE_3_2 = 'SPHERE_3_2',
  SPHERE_3_2_1 = 'SPHERE_3_2_1',
  SPHERE_3_2_2 = 'SPHERE_3_2_2',
  SPHERE_3_2_3 = 'SPHERE_3_2_3',
  SPHERE_3_2_4 = 'SPHERE_3_2_4',
  SPHERE_3_3 = 'SPHERE_3_3',
  SPHERE_3_4 = 'SPHERE_3_4',
  SPHERE_3_5 = 'SPHERE_3_5',
  SPHERE_3_6 = 'SPHERE_3_6',
  SPHERE_3_6_1 = 'SPHERE_3_6_1',
  SPHERE_3_6_2 = 'SPHERE_3_6_2',
  SPHERE_3_7 = 'SPHERE_3_7',
  SPHERE_3_8 = 'SPHERE_3_8',
  SPHERE_3_9 = 'SPHERE_3_9',
  SPHERE_3_10 = 'SPHERE_3_10',
  SPHERE_4 = 'SPHERE_4',
  SPHERE_4_1 = 'SPHERE_4_1',
  SPHERE_4_1_1 = 'SPHERE_4_1_1',
  SPHERE_4_1_2 = 'SPHERE_4_1_2',
  SPHERE_4_1_3 = 'SPHERE_4_1_3',
  SPHERE_4_2 = 'SPHERE_4_2',
  SPHERE_4_2_1 = 'SPHERE_4_2_1',
  SPHERE_4_2_2 = 'SPHERE_4_2_2',
  SPHERE_4_2_3 = 'SPHERE_4_2_3',
  SPHERE_4_2_4 = 'SPHERE_4_2_4',
  SPHERE_4_3 = 'SPHERE_4_3',
  SPHERE_4_4 = 'SPHERE_4_4',
  SPHERE_4_5 = 'SPHERE_4_5',
  SPHERE_4_6 = 'SPHERE_4_6',
  SPHERE_4_7 = 'SPHERE_4_7',
  SPHERE_4_8 = 'SPHERE_4_8',
  SPHERE_4_9 = 'SPHERE_4_9',
  SPHERE_4_10 = 'SPHERE_4_10',
}

interface AccreditationSphereItem {
  id: AccreditationSphere
  code: string
  name: string
}

export const ACCREDITATION_SPHERES: AccreditationSphereItem[] = [
  {
    id: AccreditationSphere.SPHERE_1,
    code: '1',
    name: 'Xavfli ishlab chiqarish obyektlarini qurish, kengaytirish, qayta qurish, texnik jihatdan qayta jihozlash, konservatsiyalash va tugatishga doir loyiha hujjatlarini sanoat xavfsizligi ekspertizasidan o‘tkazish. Xavfli ishlab chiqarish obyektlarini identifikatsiya qilish.',
  },
  { id: AccreditationSphere.SPHERE_1_1, code: '1.1', name: 'Ko‘mir, kon, ruda va noruda sanoati obyektlari:' },
  { id: AccreditationSphere.SPHERE_1_1_1, code: '1.1.1', name: 'Shaxta' },
  {
    id: AccreditationSphere.SPHERE_1_1_2,
    code: '1.1.2',
    name: 'Ko‘mir va ruda konlari (yerosti va yerusti) obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_1_1_3,
    code: '1.1.3',
    name: 'Boyituvchi, briketlovchi, aglomeratsialovchi fabrika va zavodlar',
  },
  { id: AccreditationSphere.SPHERE_1_1_4, code: '1.1.4', name: 'Boyitish-saralash va me’yorlash qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_1_1_5,
    code: '1.1.5',
    name: 'Shlam to‘plovchi gidrotexnika inshootlari, chiqindilarni saqlovchi, texnik suv havzalari obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_1_6, code: '1.1.6', name: 'Oltin konlari va boshqa oltin saralash fabrikalari' },
  { id: AccreditationSphere.SPHERE_1_1_7, code: '1.1.7', name: 'Oltin saralash fabrikasi va zavodlari (qurilmalari)' },
  { id: AccreditationSphere.SPHERE_1_1_8, code: '1.1.8', name: 'Konlarni texnik rekultivatsiya qilish obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_1_9,
    code: '1.1.9',
    name: 'Foydali qazilma boyliklarini qazib olish bilan bog‘liq bo‘lmagan ishlab chiqarish obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_1_1_10,
    code: '1.1.10',
    name: 'Maxsus yerosti, transport va umumiy xo‘jalik inshootlarini qurish bilan bog‘liq bo‘lgan ishlab chiqarish obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_2, code: '1.2', name: 'Neft va gaz sanoati obyektlari:' },
  {
    id: AccreditationSphere.SPHERE_1_2_1,
    code: '1.2.1',
    name: 'Neft va gazga qazilgan parametrik, qidiruv, izlov, struktur va ekspluatatsion quduqlar hamda maxsus qazilgan quduqlar',
  },
  { id: AccreditationSphere.SPHERE_1_2_2, code: '1.2.2', name: 'Yerosti gaz omborlari' },
  {
    id: AccreditationSphere.SPHERE_1_2_3,
    code: '1.2.3',
    name: 'Neft, gaz va gaz kondensati konlarini ishlatish va qurish; neft, gaz va gaz kondensatini qazib olish va tayyorlash obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_1_2_4,
    code: '1.2.4',
    name: 'Neftni, gazni va gaz kondensatini konlarda va konlar orasida tashish quvur o‘tkazgichlari',
  },
  { id: AccreditationSphere.SPHERE_1_2_5, code: '1.2.5', name: 'Magistral quvurlar' },
  {
    id: AccreditationSphere.SPHERE_1_2_6,
    code: '1.2.6',
    name: 'Kompressor va nasos stansiyalari; gaz taqsimlash stansiyalari',
  },
  { id: AccreditationSphere.SPHERE_1_2_7, code: '1.2.7', name: 'Qatlamdagi bosimni barqaror saqlab turish obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_2_8,
    code: '1.2.8',
    name: 'Neft mahsulotlarini, neftni va gaz kondensatini saqlash hamda vaqtincha saqlash obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_2_9, code: '1.2.9', name: 'Avtomobillarga yoqilg‘i quyish shoxobchalari' },
  {
    id: AccreditationSphere.SPHERE_1_3,
    code: '1.3',
    name: 'Kimyo, neft-kimyo, neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud kimyoviy xavfli ishlab chiqarish obyektlari:',
  },
  {
    id: AccreditationSphere.SPHERE_1_3_1,
    code: '1.3.1',
    name: 'Noorganik moddalar, ammiak, mineral o‘g‘itlar ishlab chiqarish obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_1_3_2,
    code: '1.3.2',
    name: 'Neft va gazni qayta ishlash sanoati ishlab chiqarish va obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_3_3, code: '1.3.3', name: 'Organik sintez ishlab chiqarish obyektlari' },
  { id: AccreditationSphere.SPHERE_1_3_4, code: '1.3.4', name: 'Sellyuloza qog‘oz ishlab chiqarish obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_3_5,
    code: '1.3.5',
    name: 'Kimyoviy tolalar, polimer materiallar, plastmassa va ulardan tayyorlanadigan mahsulotlarni ishlab chiqarish obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_3_6, code: '1.3.6', name: 'Kriogen texnologiyalar obyektlari' },
  { id: AccreditationSphere.SPHERE_1_3_7, code: '1.3.7', name: 'Ammiakli sovitish qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_1_3_8,
    code: '1.3.8',
    name: 'Elektroliz usulida vodorod va kislorod ishlab chiqarish obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_3_9, code: '1.3.9', name: 'Lok-bo‘yoq mahsulotlari ishlab chiqarish obyektlari' },
  { id: AccreditationSphere.SPHERE_1_3_10, code: '1.3.10', name: 'Spirt ishlab chiqarish obyektlari' },
  { id: AccreditationSphere.SPHERE_1_3_11, code: '1.3.11', name: 'Yogʻ-moy ishlab chiqarish obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_3_12,
    code: '1.3.12',
    name: 'Havoni parchalashda hosil bo‘lgan mahsulotlarni olish va saqlash obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_3_13, code: '1.3.13', name: 'Suvni xlor bilan qayta ishlash obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_3_14,
    code: '1.3.14',
    name: 'Portlash-yonish xavfi mavjud va kimyoviy xavfli mahsulotlarni (moddalarni) quyish, to‘kish obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_1_4,
    code: '1.4',
    name: 'Bosimi 0,05 MPa yoki suvning isitish harorati 110 °S dan yuqori bo‘lgan jihozdan foydalaniladigan ishlab chiqarish obyektlari:',
  },
  {
    id: AccreditationSphere.SPHERE_1_4_1,
    code: '1.4.1',
    name: 'Bugʻ va suv isitish qozonlari (ishchi muhit turidan qat’i nazar)',
  },
  { id: AccreditationSphere.SPHERE_1_4_2, code: '1.4.2', name: 'Bosim ostida ishlovchi idishlar' },
  { id: AccreditationSphere.SPHERE_1_4_3, code: '1.4.3', name: 'Bugʻ va issiq suv quvur o‘tkazgichlar' },
  {
    id: AccreditationSphere.SPHERE_1_5,
    code: '1.5',
    name: 'Ko‘chmas asosga o‘rnatilgan yuk ko‘tarish mexanizmlari, eskalatorlar, po‘lat arqonli osma yo‘llar, funikulyorlardan foydalanadigan ishlab chiqarish obyektlari:',
  },
  { id: AccreditationSphere.SPHERE_1_5_1, code: '1.5.1', name: 'Yuk ko‘tarish kranlari va mexanizmlari' },
  { id: AccreditationSphere.SPHERE_1_5_2, code: '1.5.2', name: 'Ekskalatorlar' },
  {
    id: AccreditationSphere.SPHERE_1_5_3,
    code: '1.5.3',
    name: 'Yuk va yo‘lovchilar uchun osma po‘lat arqonli yo‘llar',
  },
  { id: AccreditationSphere.SPHERE_1_5_4, code: '1.5.4', name: 'Funikulyorlar' },
  {
    id: AccreditationSphere.SPHERE_1_6,
    code: '1.6',
    name: 'Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta’minoti (gaz taqsimlash, gaz iste’moli) obyektlari:',
  },
  {
    id: AccreditationSphere.SPHERE_1_6_1,
    code: '1.6.1',
    name: 'Suyultirilgan uglevodorod gazlarini saqlash va taqsimlash obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_1_6_2,
    code: '1.6.2',
    name: 'Avtomobillarga suyultirilgan uglevodorod gaz to‘ldirish shoxobchalari',
  },
  {
    id: AccreditationSphere.SPHERE_1_6_3,
    code: '1.6.3',
    name: 'Avtomobillarga gaz to‘ldirish kompressor shoxobchalari',
  },
  {
    id: AccreditationSphere.SPHERE_1_6_4,
    code: '1.6.4',
    name: 'Bosimi 12 kgf/kv.sm gacha bo‘lgan gaz taqsimlash tizimlarining gaz tarmoqlari',
  },
  { id: AccreditationSphere.SPHERE_1_6_5, code: '1.6.5', name: 'Gaz iste’moli tizimlarining gaz tarmoqlari' },
  { id: AccreditationSphere.SPHERE_1_7, code: '1.7', name: 'Metallurgiya sanoati obyektlari:' },
  {
    id: AccreditationSphere.SPHERE_1_7_1,
    code: '1.7.1',
    name: 'Qora metallar quyish sanoati, po‘lat ishlab chiqarish obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_7_2, code: '1.7.2', name: 'Rangli metallar quyish sanoati obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_8,
    code: '1.8',
    name: 'O‘simlik xomashyosini saqlash va qayta ishlash obyektlari:',
  },
  {
    id: AccreditationSphere.SPHERE_1_8_1,
    code: '1.8.1',
    name: 'Qabul qilish, saqlash, quritish, qayta ishlash, alohida turuvchi qabul qilish va uzatish uskunasi, qabul qiluvchi-tozalash minorasi, alohida turuvchi don quritish uchastkalari, elevatorlar, silos tipidagi omborlar, qopsiz saqlash omborlari, solod ishlab chiqarish obyektlari, qayta ishlovchi va tayyorlovchi (maydalovchi) bo‘limlar, shu jumladan oziq-ovqat sanoati korxonalari',
  },
  { id: AccreditationSphere.SPHERE_1_8_2, code: '1.8.2', name: 'Un, yorma ishlab chiqarish obyektlari' },
  { id: AccreditationSphere.SPHERE_1_8_3, code: '1.8.3', name: 'Omuxta yem ishlab chiqarish obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_8_4,
    code: '1.8.4',
    name: 'Qopsiz qabul qilish, unni silos va bunkerlarda saqlash, non, makaron va qandolat mahsulotlarini ishlab chiqarish uchun unni tortish hamda elash obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_1_8_5,
    code: '1.8.5',
    name: 'Un, yorma, non va makaron ishlab chiqarish korxonalari uchun qopli idishlarni tozalash va saralash obyektlari',
  },
  { id: AccreditationSphere.SPHERE_1_8_6, code: '1.8.6', name: 'Jo‘xorini kalibrlovchi obyektlar' },
  { id: AccreditationSphere.SPHERE_1_8_7, code: '1.8.7', name: 'Urug‘lik donlarni qayta ishlovchi obyektlar' },
  { id: AccreditationSphere.SPHERE_1_8_8, code: '1.8.8', name: 'Tamaki mahsulotlarini tayyorlash obyektlari' },
  {
    id: AccreditationSphere.SPHERE_1_9,
    code: '1.9',
    name: 'Foydali qazilma konlarini qidirish va izlash bilan bog‘liq geologiya-razvedka obyektlari (uglevodorod xomashyosi bo‘lmagan)',
  },
  {
    id: AccreditationSphere.SPHERE_1_10,
    code: '1.10',
    name: 'Sanoatda qo‘llanadigan portlovchi moddalarni ishlab chiqarish, sinash va saqlash bilan bog‘liq bo‘lgan obyektlar',
  },
  {
    id: AccreditationSphere.SPHERE_2,
    code: '2',
    name: 'Xavfli ishlab chiqarish obyektlarida qo‘llanadigan texnik qurilmalarni sanoat xavfsizligi ekspertizasidan o‘tkazish',
  },
  {
    id: AccreditationSphere.SPHERE_2_1,
    code: '2.1',
    name: 'Ko‘mir, kon, ruda va noruda sanoatidagi texnik qurilmalar:',
  },
  { id: AccreditationSphere.SPHERE_2_1_1, code: '2.1.1', name: 'Shaxtada qo‘llanadigan qurilmalar' },
  {
    id: AccreditationSphere.SPHERE_2_1_2,
    code: '2.1.2',
    name: 'Ko‘mir va ruda konlari (yerosti va yerusti) obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_1_3,
    code: '2.1.3',
    name: 'Boyituvchi, briketlovchi, aglomeratsialovchi fabrika va zavodlar qurilmalari',
  },
  { id: AccreditationSphere.SPHERE_2_1_4, code: '2.1.4', name: 'Boyitish-saralash va me’yorlash qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_2_1_5,
    code: '2.1.5',
    name: 'Shlam to‘plovchi gidrotexnika inshootlari, chiqindilarni saqlovchi va texnik suv havzalari obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_1_6,
    code: '2.1.6',
    name: 'Oltin konlari va boshqa oltin saralash fabrikalarining qurilmalari',
  },
  { id: AccreditationSphere.SPHERE_2_1_7, code: '2.1.7', name: 'Oltin saralash fabrikasi va zavodlari qurilmalari' },
  { id: AccreditationSphere.SPHERE_2_1_8, code: '2.1.8', name: 'Konlarni texnik rekultivatsiya qilish qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_2_1_9,
    code: '2.1.9',
    name: 'Foydali qazilma boyliklari qazib olish bilan bog‘liq bo‘lmagan ishlab chiqarish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_1_10,
    code: '2.1.10',
    name: 'Maxsus yerosti, transport va umumiy xo‘jalik inshootlarini qurish bilan bog‘liq bo‘lgan ishlab chiqarish obyektlarining qurilmalari',
  },
  { id: AccreditationSphere.SPHERE_2_2, code: '2.2', name: 'Neft va gaz sanoatidagi texnik qurilmalar:' },
  {
    id: AccreditationSphere.SPHERE_2_2_1,
    code: '2.2.1',
    name: 'Quduqlarni burg‘ilashda, ta’mirlashda va ishga tushirishda qo‘llanadigan qurilmalar',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_2,
    code: '2.2.2',
    name: 'Neft va gaz quduqlarini ishlatishda qo‘llanadigan qurilmalar',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_3,
    code: '2.2.3',
    name: 'Qatlamdagi bosimni va qatlamga hamda quduqqa ta’sir qiluvchi omillarni saqlashda qo‘llanadigan qurilmalar',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_4,
    code: '2.2.4',
    name: 'Neft va gazni yetkazib beruvchi stansiyalarda qo‘llanadigan qurilmalar',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_5,
    code: '2.2.5',
    name: 'Magistral quvurlar tizimini qurishda, ishlatishda va ta’mirlashda qo‘llanadigan qurilmalar',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_6,
    code: '2.2.6',
    name: 'Gaz va neft mahsulotlari quvurlari; kon va konlararo quvurlar',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_7,
    code: '2.2.7',
    name: 'Kompozit va po‘lat quvurlar qismlari va quvurlari, shu jumladan, tiqin (zapor), me’yorlovchi va himoyalovchi armaturalar qismlari',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_8,
    code: '2.2.8',
    name: 'Neft, kondensat va neft mahsulotlari uchun rezervuarlar hamda ularning qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_2_9,
    code: '2.2.9',
    name: 'Kompressor, nasos va gaz taqsimlash stansiyalari qurilmalari',
  },
  { id: AccreditationSphere.SPHERE_2_2_10, code: '2.2.10', name: 'Neft va gazni yig‘ish va tayyorlash qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_2_3,
    code: '2.3',
    name: 'Kimyo, neft-kimyo, neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud va kimyoviy xavfli ishlab chiqarish obyektlaridagi texnik qurilmalar:',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_1,
    code: '2.3.1',
    name: 'Noorganik moddalar, ammiak, mineral o‘g‘itlar ishlab chiqarish obyektlari qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_2,
    code: '2.3.2',
    name: 'Neft va gazni qayta ishlash obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_3,
    code: '2.3.3',
    name: 'Organik sintez ishlab chiqarish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_4,
    code: '2.3.4',
    name: 'Sellyuloza qog‘oz ishlab chiqarish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_5,
    code: '2.3.5',
    name: 'Kimyoviy tolalar, polimer materiallar, plastmassa va ulardan tayyorlanadigan mahsulotlar ishlab chiqarish obyektlarining qurilmalari',
  },
  { id: AccreditationSphere.SPHERE_2_3_6, code: '2.3.6', name: 'Kriogen texnologiyasi qurilmalari' },
  { id: AccreditationSphere.SPHERE_2_3_7, code: '2.3.7', name: 'Ammiakli sovitish qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_2_3_8,
    code: '2.3.8',
    name: 'Elektroliz usulida vodorod va kislorod ishlab chiqarish obyektlari qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_9,
    code: '2.3.9',
    name: 'Lok-bo‘yoq mahsulotlari ishlab chiqarish obyektlarining qurilmalari',
  },
  { id: AccreditationSphere.SPHERE_2_3_10, code: '2.3.10', name: 'Spirt ishlab chiqarish obyektlarining qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_2_3_11,
    code: '2.3.11',
    name: 'Yogʻ-moy ishlab chiqarish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_12,
    code: '2.3.12',
    name: 'Havoni parchalashda hosil bo‘lgan mahsulotlarni olish va saqlash obyektlari qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_13,
    code: '2.3.13',
    name: 'Suvni xlor bilan qayta ishlash obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_3_14,
    code: '2.3.14',
    name: 'Portlash-yonish xavfi mavjud va kimyoviy xavfli mahsulotlarni (moddalarni) quyish, to‘kish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_4,
    code: '2.4',
    name: 'Bosimi 0,05 MPa dan yuqori bo‘lgan yoki suvning harorati 110 °S dan yuqori bo‘lgan sharoitda ishlaydigan texnik qurilmalar:',
  },
  {
    id: AccreditationSphere.SPHERE_2_4_1,
    code: '2.4.1',
    name: 'Suv isitish va bugʻ qozonlari hamda ularning qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_4_2,
    code: '2.4.2',
    name: 'Bosim 0,05 MPa dan yuqori bo‘lgan bosim ostida ishlovchi idishlar',
  },
  {
    id: AccreditationSphere.SPHERE_2_4_3,
    code: '2.4.3',
    name: 'Bosim 0,05 MPa dan va suvning harorati 110 °S dan yuqori bo‘lgan bugʻ va issiq suv quvurlari',
  },
  { id: AccreditationSphere.SPHERE_2_4_4, code: '2.4.4', name: 'Avtonom bugʻ qizdirgichlar' },
  { id: AccreditationSphere.SPHERE_2_4_5, code: '2.4.5', name: 'Avtonom ekonomayzerlar' },
  {
    id: AccreditationSphere.SPHERE_2_5,
    code: '2.5',
    name: 'Ko‘chmas asosga o‘rnatilgan yuk ko‘tarish mexanizmlari, eskalatorlar, po‘lat arqonli osma yo‘llar, funikulyorlar:',
  },
  { id: AccreditationSphere.SPHERE_2_5_1, code: '2.5.1', name: 'Yuk ko‘tarish kranlari' },
  { id: AccreditationSphere.SPHERE_2_5_2, code: '2.5.2', name: 'Kran-manipulyatorlar' },
  { id: AccreditationSphere.SPHERE_2_5_3, code: '2.5.3', name: 'Quvuryotqizgich kranlar' },
  { id: AccreditationSphere.SPHERE_2_5_4, code: '2.5.4', name: 'Ko‘targichlar (vishkalar)' },
  { id: AccreditationSphere.SPHERE_2_5_5, code: '2.5.5', name: 'Qurilish ko‘targichlari' },
  { id: AccreditationSphere.SPHERE_2_5_6, code: '2.5.6', name: 'Liftlar' },
  { id: AccreditationSphere.SPHERE_2_5_7, code: '2.5.7', name: 'Nogironlarni ko‘tarishga mo‘ljallangan platformalar' },
  {
    id: AccreditationSphere.SPHERE_2_5_8,
    code: '2.5.8',
    name: 'Yuk va yo‘lovchilar uchun osma po‘lat arqonli yo‘llar',
  },
  { id: AccreditationSphere.SPHERE_2_5_9, code: '2.5.9', name: 'Funikulyorlar' },
  { id: AccreditationSphere.SPHERE_2_5_10, code: '2.5.10', name: 'Ekskalatorlar' },
  {
    id: AccreditationSphere.SPHERE_2_5_11,
    code: '2.5.11',
    name: 'Yuk ko‘tarish mexanizmlari va idishlar (metallurgiyadan tashqari)',
  },
  {
    id: AccreditationSphere.SPHERE_2_6,
    code: '2.6',
    name: 'Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta’minoti (gaz taqsimlash, gaz iste’moli) obyektlarining texnik qurilmalari:',
  },
  {
    id: AccreditationSphere.SPHERE_2_6_1,
    code: '2.6.1',
    name: 'Suyultirilgan uglevodorod gazlarini saqlash va taqsimlash obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_6_2,
    code: '2.6.2',
    name: 'Avtomobillarga suyultirilgan uglevodorod gaz to‘ldirish shoxobchalarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_6_3,
    code: '2.6.3',
    name: 'Avtomobillarga gaz to‘ldirish kompressor shoxobchalarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_6_4,
    code: '2.6.4',
    name: 'Bosimi 12 kgf/kv.sm gacha bo‘lgan gaz taqsimlash tizimlari',
  },
  { id: AccreditationSphere.SPHERE_2_6_5, code: '2.6.5', name: 'Gaz iste’moli tizimlari' },
  { id: AccreditationSphere.SPHERE_2_7, code: '2.7', name: 'Metallurgiya sanoati texnik qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_2_7_1,
    code: '2.7.1',
    name: 'Qora metallar quyish, po‘lat ishlab chiqarish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_7_2,
    code: '2.7.2',
    name: 'Rangli metallar quyish sanoati obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_8,
    code: '2.8',
    name: 'O‘simlik xomashyosini saqlash va qayta ishlash obyektlarining texnik qurilmalari:',
  },
  { id: AccreditationSphere.SPHERE_2_8_1, code: '2.8.1', name: 'Elevator ombori qurilmalari' },
  { id: AccreditationSphere.SPHERE_2_8_2, code: '2.8.2', name: 'Un ishlab chiqarish korxonalari qurilmalari' },
  { id: AccreditationSphere.SPHERE_2_8_3, code: '2.8.3', name: 'Yorma ishlab chiqarish obyektlarining qurilmalari' },
  {
    id: AccreditationSphere.SPHERE_2_8_4,
    code: '2.8.4',
    name: 'Omuxta yem ishlab chiqarish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_8_5,
    code: '2.8.5',
    name: 'Qopsiz qabul qilish, unni silos va bunkerlarda saqlash, non, makaron va qandolat mahsulotlarini ishlab chiqarish uchun unni tortish va elash obyektlari qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_8_6,
    code: '2.8.6',
    name: 'O‘simlik xomashyosini qabul qilish, saqlash, quritish, qayta ishlash, alohida turuvchi qabul qilish va uzatish uskunasi, qabul qiluvchi tozalash minorasi, alohida turuvchi don quritish uchastkalari, elevatorlar, silos tipidagi omborlar, qopsiz saqlash omborlari, solod ishlab chiqarish obyektlari, qayta ishlovchi hamda tayyorlovchi (maydalovchi) bo‘limlar, shu jumladan, oziq-ovqat sanoati korxonalari qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_8_7,
    code: '2.8.7',
    name: 'Jo‘xorini kalibrlovchi ishlab chiqarish obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_8_8,
    code: '2.8.8',
    name: 'Urug‘lik donlarni qayta ishlaydigan obyektlarning qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_8_9,
    code: '2.8.9',
    name: 'Tamaki tayyorlash liniyalari obyektlarining qurilmalari',
  },
  {
    id: AccreditationSphere.SPHERE_2_9,
    code: '2.9',
    name: 'Foydali qazilma konlarini qidirish va izlash bilan bog‘liq geologiya-razvedka obyektlaridagi texnik qurilmalar (uglevodorod xomashyosi bo‘lmagan)',
  },
  {
    id: AccreditationSphere.SPHERE_2_10,
    code: '2.10',
    name: 'Sanoatga mo‘ljallangan portlovchi moddalarni ishlab chiqarish, sinash va saqlashda qo‘llanadigan texnik qurilmalar',
  },
  {
    id: AccreditationSphere.SPHERE_3,
    code: '3',
    name: 'Xavfli ishlab chiqarish obyektidagi binolar va inshootlarni sanoat xavfsizligi ekspertizasidan o‘tkazish',
  },
  { id: AccreditationSphere.SPHERE_3_1, code: '3.1', name: 'Ko‘mir, kon-ruda va noruda sanoatlarida:' },
  { id: AccreditationSphere.SPHERE_3_1_1, code: '3.1.1', name: 'Yerusti kompleks bino va inshootlar' },
  { id: AccreditationSphere.SPHERE_3_1_2, code: '3.1.2', name: 'Yerosti inshootlari' },
  {
    id: AccreditationSphere.SPHERE_3_1_3,
    code: '3.1.3',
    name: 'Foydali qazilma boyliklarini qazib olish bilan bog‘liq bo‘lmagan ishlab chiqarish obyektlaridagi bino va inshootlar',
  },
  { id: AccreditationSphere.SPHERE_3_2, code: '3.2', name: 'Neft va gaz sanoati obyektlarida:' },
  {
    id: AccreditationSphere.SPHERE_3_2_1,
    code: '3.2.1',
    name: 'Quduqlarni qazish va ta’mirlash bilan bog‘liq bo‘lgan obyektlardagi bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_2_2,
    code: '3.2.2',
    name: 'Neft va gaz qazib olish va ularni tayyorlash obyektlaridagi bino va inshootlar',
  },
  { id: AccreditationSphere.SPHERE_3_2_3, code: '3.2.3', name: 'Magistral quvurlar obyektlaridagi bino va inshootlar' },
  {
    id: AccreditationSphere.SPHERE_3_2_4,
    code: '3.2.4',
    name: 'Neft mahsulotlarini, kondensat va neftni saqlash va uzatish obyektlaridagi bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_3,
    code: '3.3',
    name: 'Kimyo, neft-kimyo va neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud kimyoviy xavfli ishlab chiqarish obyektlaridagi bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_4,
    code: '3.4',
    name: 'Bosimi 0,05 MPa dan yuqori bo‘lgan yoki suvning isish harorati 110 °S dan yuqori bo‘lgan qurilmalar joylashgan bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_5,
    code: '3.5',
    name: 'Ko‘chmas asosga o‘rnatilgan yuk ko‘tarish mexanizmlari, eskalatorlar, po‘lat arqonli osma yo‘llar, funikulyorlardan foydalanadigan ishlab chiqarish obyektlaridagi bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_6,
    code: '3.6',
    name: 'Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta’minoti (gaz taqsimlash, gaz iste’moli) obyektlaridagi bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_6_1,
    code: '3.6.1',
    name: 'Gaz jihozlari o‘rnatilgan bino va inshootlar (qozonxonalar, sexlar)',
  },
  {
    id: AccreditationSphere.SPHERE_3_6_2,
    code: '3.6.2',
    name: 'Avtomobillarga gaz (suyultirilgan uglevodorod gaz) to‘ldirish shoxobchalarining bino va inshootlari',
  },
  { id: AccreditationSphere.SPHERE_3_7, code: '3.7', name: 'Metallurgiya sanoati obyektlaridagi bino va inshootlar' },
  {
    id: AccreditationSphere.SPHERE_3_8,
    code: '3.8',
    name: 'O‘simlik xomashyosini saqlash hamda qayta ishlash obyektlaridagi bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_9,
    code: '3.9',
    name: 'Foydali qazilma konlarini qidirish va izlash bilan bog‘liq geologiya-razvedka obyektlaridagi (uglevodorod xomashyosi bo‘lmagan) bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_3_10,
    code: '3.10',
    name: 'Sanoatda qo‘llaniladigan portlovchi moddalarni ishlab chiqarish, sinash va saqlash bilan bog‘liq bo‘lgan obyektlardagi bino va inshootlar',
  },
  {
    id: AccreditationSphere.SPHERE_4,
    code: '4',
    name: 'Sanoat xavfsizligi deklaratsiyasini ishlab chiqish. Sanoat xavfsizligi deklaratsiyasini sanoat xavfsizligi ekspertizasidan o‘tkazish.',
  },
  { id: AccreditationSphere.SPHERE_4_1, code: '4.1', name: 'Ko‘mir, kon, ruda va noruda sanoati obyektlari:' },
  { id: AccreditationSphere.SPHERE_4_1_1, code: '4.1.1', name: 'Yerusti ishlab chiqarish obyektlari' },
  { id: AccreditationSphere.SPHERE_4_1_2, code: '4.1.2', name: 'Yerosti ishlab chiqarish obyektlari' },
  {
    id: AccreditationSphere.SPHERE_4_1_3,
    code: '4.1.3',
    name: 'Foydali qazilma boyliklarini qazib olish bilan bog‘liq bo‘lmagan ishlab chiqarish obyektlari',
  },
  { id: AccreditationSphere.SPHERE_4_2, code: '4.2', name: 'Neft va gaz sanoati obyektlari:' },
  {
    id: AccreditationSphere.SPHERE_4_2_1,
    code: '4.2.1',
    name: 'Quduqlarni qazish va ta’mirlash bilan bog‘liq bo‘lgan obyektlar',
  },
  {
    id: AccreditationSphere.SPHERE_4_2_2,
    code: '4.2.2',
    name: 'Neft va gaz qazib olish va ularni tayyorlash obyektlari',
  },
  { id: AccreditationSphere.SPHERE_4_2_3, code: '4.2.3', name: 'Magistral quvurlar obyektlari' },
  {
    id: AccreditationSphere.SPHERE_4_2_4,
    code: '4.2.4',
    name: 'Neft mahsulotlarini, kondensat va neftni saqlash va uzatish obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_4_3,
    code: '4.3',
    name: 'Kimyo, neft-kimyo, neft va gazni qayta ishlash sanoati hamda portlash-yonish xavfi mavjud kimyoviy xavfli ishlab chiqarish obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_4_4,
    code: '4.4',
    name: 'Bosimi 0,05 MPa dan yuqori yoki suvning harorati 110 °S dan yuqori bo‘lgan qurilmalardan foydalanadigan ishlab chiqarish obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_4_5,
    code: '4.5',
    name: 'Ko‘chmas asosga o‘rnatilgan yuk ko‘tarish mexanizmlari, eskalatorlar, po‘lat arqonli osma yo‘llar, funikulyorlardan foydalanadigan ishlab chiqarish obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_4_6,
    code: '4.6',
    name: 'Tabiiy va suyultirilgan uglevodorod gazlaridan foydalanuvchi gaz ta’minoti (gaz taqsimlash, gaz iste’moli) obyektlari',
  },
  { id: AccreditationSphere.SPHERE_4_7, code: '4.7', name: 'Metallurgiya sanoati obyektlari' },
  {
    id: AccreditationSphere.SPHERE_4_8,
    code: '4.8',
    name: 'O‘simlik xomashyosini saqlash va qayta ishlash obyektlari',
  },
  {
    id: AccreditationSphere.SPHERE_4_9,
    code: '4.9',
    name: 'Foydali qazilma konlarini qidirish va izlash bilan bog‘liq geologiya-razvedka obyektlari (uglevodorod xomashyosi bo‘lmagan)',
  },
  {
    id: AccreditationSphere.SPHERE_4_10,
    code: '4.10',
    name: 'Sanoatda qo‘llaniladigan portlovchi moddalarni ishlab chiqarish, sinash va saqlash bilan bog‘liq bo‘lgan obyektlar',
  },
]

export const ACCREDITATION_SPHERE_LABELS: Record<string, string> = Object.fromEntries(
  ACCREDITATION_SPHERES.map((s) => [s.id, `${s.code}. ${s.name}`])
)

export const ACCREDITATION_SPHERE_OPTIONS = ACCREDITATION_SPHERES.map((s) => ({
  id: s.id,
  name: `${s.code}. ${s.name}`,
}))
