import {
  ApplicationCardItem,
  ApplicationCategory,
  ApplicationTypeEnum,
  MainApplicationCategory,
} from '@/entities/create-application'
import { FileInput, FileOutput, FilePlus } from 'lucide-react'

export const APPLICATION_CATEGORIES = [
  {
    id: ApplicationCategory.HF,
    name: 'XICHO',
  },
  {
    id: ApplicationCategory.EQUIPMENTS,
    name: 'Xavfli obyektlar va qurilmalar',
  },
  {
    id: ApplicationCategory.INM,
    name: 'INM',
  },
  {
    id: ApplicationCategory.XRAY,
    name: 'Rentgen',
  },
  // {
  //   id: ApplicationCategory.ACCREDITATION,
  //   name: 'Akkreditatsiya',
  // },
  // {
  //   id: ApplicationCategory.ATTESTATION_PREVENTION,
  //   name: 'Attestatsiya',
  // },
  // {
  //   id: ApplicationCategory.CADASTRE,
  //   name: 'Kadastr',
  // },
]

export const MAIN_APPLICATION_BY_CATEGORY = {
  [ApplicationCategory.HF]: [],
  [ApplicationCategory.EQUIPMENTS]: [
    {
      id: MainApplicationCategory.REGISTER,
      title: 'Xavfli obyekt va qurilmalarni ro‘yxatga olish',
      description: 'Xavfli obyekt va qurilmalarni davlat ro‘yxatiga olish ariza shakllari',
      icon: FileInput,
    },
    {
      id: MainApplicationCategory.UNREGISTER,
      title: 'Xavfli obyekt va qurilmalarni ro‘yxatdan chiqarish',
      description: 'Xavfli obyekt va qurilmalarni ro‘yxatdan chiqarish ariza shakllari',
      icon: FileOutput,
    },
    {
      id: MainApplicationCategory.REREGISTER,
      title: 'Xavfli obyekt va qurilmalarni qayta ro‘yxatdan o‘tkazish',
      description: 'Xavfli obyekt va qurilmalarni qayta ro‘yxatdan o‘tkazish ariza shakllari',
      icon: FilePlus,
    },
  ],
  [ApplicationCategory.INM]: [],
  [ApplicationCategory.XRAY]: [],
  // [ApplicationCategory.CADASTRE]: [],
  // [ApplicationCategory.ACCREDITATION]: [],
  // [ApplicationCategory.ATTESTATION_PREVENTION]: [],
  [ApplicationCategory.ILLEGAL]: [],
}

export const REPORTS_DATA: ApplicationCardItem[] = [
  {
    id: 1,
    title: '1-hisobot',
    description: 'Jismoniy va yuridik shaxslardan yuborilgan arizalarni hududlar kesimida taqsimlanishi',
    type: ApplicationTypeEnum.REPORT_1,
    icon: 'factoryRegisterIcon',
  },
  {
    id: 2,
    title: '2-hisobot',
    description:
      'Jismoniy va yuridik shaxslardan yuborilgan arizalarni turlari bo‘yicha hududlar kesimida taqsimlanishi',
    type: ApplicationTypeEnum.REPORT_2,
    icon: 'factoryDeregisterIcon',
  },
  {
    id: 3,
    title: '3-hisobot',
    description:
      'Davlat ro‘yxatiga kiritilgan va ro‘yxatdan chiqarilgan XICHO, qurilmalar va IIMlarni hududlar kesimida taqsimlanishi',
    type: ApplicationTypeEnum.REPORT_3,
    icon: 'factoryUpdateIcon',
  },
  {
    id: 4,
    title: '4-hisobot',
    description:
      'Davlat ro‘yxatidan o‘tqazilgan amaldagi XICHO, INM, Bosim ostidagi idishlar va qurilmalar to‘g‘risida sanalar bo‘yicha maʼlumot',
    type: ApplicationTypeEnum.REPORT_4,
    icon: 'escalator',
  },
]

export const APPLICATIONS_DATA: ApplicationCardItem[] = [
  {
    id: 1,
    title: 'XICHOni ro‘yxatga olish',
    description: 'XICHOni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.HF,
    type: ApplicationTypeEnum.REGISTER_HF,
    icon: 'factoryRegisterIcon',
  },
  {
    id: 2,
    title: 'XICHOni ro‘yxatga olish',
    description: 'XICHOni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.ILLEGAL,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_HF,
    icon: 'factoryRegisterIcon',
  },
  {
    id: 3,
    title: 'XICHOni ro‘yxatdan chiqarish',
    description: 'XICHOni ro‘yxatdan chiqarish ariza shakli',
    category: ApplicationCategory.HF,
    type: ApplicationTypeEnum.DEREGISTER_HF,
    icon: 'factoryDeregisterIcon',
  },
  {
    id: 4,
    title: 'XICHO reyestriga o‘zgartirish kiritish',
    description: 'XICHO reyestriga o‘zgartirish kiritish uchun ariza shakli',
    category: ApplicationCategory.HF,
    type: ApplicationTypeEnum.RE_REGISTER_HF,
    icon: 'factoryUpdateIcon',
  },
  {
    id: 5,
    title: 'Qurilmani ro‘yxatdan chiqarish',
    name: 'Qurilma',
    description: 'Qurilmani ro‘yxatdan chiqarish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.DEREGISTER_EQUIPMENT,
    parentId: MainApplicationCategory.UNREGISTER,
    icon: 'boiler',
  },
  {
    id: 6,
    title: 'Qurilmani qayta ro‘yxatga olish',
    name: 'Qurilma',
    description: 'Qurilmani qayta ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.RE_REGISTER_EQUIPMENT,
    parentId: MainApplicationCategory.REREGISTER,
    icon: 'boiler',
  },
  {
    id: 7,
    title: 'Kranni ro‘yxatdan chiqarish',
    name: 'Kran',
    description: 'Kranni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_CRANE,
    icon: 'crane',
  },
  {
    id: 8,
    title: 'Bosim ostida ishlovchi idishni ro‘yxatdan chiqarish',
    name: 'Bosim ostida ishlovchi idish',
    description: 'Bosim ostida ishlovchi idishni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_CONTAINER,
    icon: 'pressureVessel',
  },
  {
    id: 9,
    title: 'Bug‘ qozonni ro‘yxatdan chiqarish',
    name: 'Bug‘ qozon',
    description: 'Bug‘ qozonlarini ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_BOILER,
    icon: 'boiler',
  },
  {
    id: 10,
    title: 'Liftni ro‘yxatdan chiqarish',
    name: 'Lift',
    description: 'Liftni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_ELEVATOR,
    icon: 'elevator',
  },
  {
    id: 11,
    title: 'Eskalatorni ro‘yxatdan chiqarish',
    name: 'Eskalator',
    description: 'Eskalatorni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_ESCALATOR,
    icon: 'escalator',
  },
  {
    id: 12,
    title: 'Attraksion pasportini ro‘yxatdan chiqarish',
    name: 'Attraksion pasporti',
    description: 'Attraksion pasportlarini ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_ATTRACTION_PASSPORT,
    icon: 'passport',
  },
  {
    id: 13,
    title: 'Attraksionni ro‘yxatdan chiqarish',
    name: 'Attraksion',
    description: 'Attraksion qurilmalarini ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_ATTRACTION,
    icon: 'attraction',
  },
  {
    id: 14,
    title: 'Quvurni ro‘yxatdan chiqarish',
    name: 'Quvur',
    description: 'Quvurlarni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_PIPELINE,
    icon: 'pipeSystem',
  },
  {
    id: 15,
    title: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatdan chiqarish',
    name: 'Bosim ostida ishlovchi idish (kimyo)',
    description: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_CHEMICAL_CONTAINER,
    icon: 'chemicalVessel',
  },
  {
    id: 16,
    title: 'Bug‘ va issiq suv quvurlarini ro‘yxatdan chiqarish',
    name: 'Bug‘ va issiq suv quvuri',
    description: 'Bug‘ va issiq suv quvurlarini ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_HEAT_PIPELINE,
    icon: 'steamPipe',
  },
  {
    id: 17,
    title: 'Qozon utilizatorlarini ro‘yxatdan chiqarish',
    name: 'Qozon utilizatorlarini',
    description: 'Qozon utilizatorlarini ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_BOILER_UTILIZER,
    icon: 'recycleBoiler',
  },
  {
    id: 18,
    title: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatdan chiqarish',
    name: 'Bosim ostida ishlovchi idishlarni (SUG)',
    description: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_LPG_CONTAINER,
    icon: 'gasVessel',
  },
  {
    id: 19,
    title: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatdan chiqarish',
    name: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilma',
    description:
      'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_LPG_POWERED,
    icon: 'naturalGas',
  },
  {
    id: 20,
    title: 'Yuk ko‘targichni ro‘yxatdan chiqarish',
    name: 'Yuk ko‘targich',
    description: 'Yuk ko‘targichni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_HOIST,
    icon: 'heavyLift',
  },
  {
    id: 21,
    title: 'Osma arqonli yuruvchi yo‘lni ro‘yxatdan chiqarish',
    name: 'Osma arqonli yuruvchi yo‘l',
    description: 'Osma arqonli yuruvchi yo‘lni ro‘yxatdan chiqarish ariza shakli',
    type: ApplicationTypeEnum.DEREGISTER_CABLEWAY,
    icon: 'cableway',
  },
  {
    id: 22,
    title: 'Kranni qayta ro‘yxatga olish',
    name: 'Kran',
    description: 'Kranni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_CRANE,
    icon: 'crane',
  },
  {
    id: 23,
    title: 'Bosim ostida ishlovchi idishni qayta ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish',
    description: 'Bosim ostida ishlovchi idishni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_CONTAINER,
    icon: 'pressureVessel',
  },
  {
    id: 24,
    title: 'Bug‘ qozonni qayta ro‘yxatga olish',
    name: 'Bug‘ qozon',
    description: 'Bug‘ qozonlarini qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_BOILER,
    icon: 'boiler',
  },
  {
    id: 25,
    title: 'Liftni qayta ro‘yxatga olish',
    name: 'Lift',
    description: 'Liftni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_ELEVATOR,
    icon: 'elevator',
  },
  {
    id: 26,
    title: 'Eskalatorni qayta ro‘yxatga olish',
    name: 'Eskalator',
    description: 'Eskalatorni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_ESCALATOR,
    icon: 'escalator',
  },
  {
    id: 27,
    title: 'Attraksion pasportini qayta ro‘yxatga olish',
    name: 'Attraksion pasporti',
    description: 'Attraksion pasportlarini qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_ATTRACTION_PASSPORT,
    icon: 'passport',
  },
  {
    id: 28,
    title: 'Attraksionni qayta ro‘yxatga olish',
    name: 'Attraksion',
    description: 'Attraksion qurilmalarini qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_ATTRACTION,
    icon: 'attraction',
  },
  {
    id: 29,
    title: 'Quvurni qayta ro‘yxatga olish',
    name: 'Quvur',
    description: 'Quvurlarni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_PIPELINE,
    icon: 'pipeSystem',
  },
  {
    id: 30,
    title: 'Bosim ostida ishlovchi idishlarni (kimyo) qayta ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish (kimyo)',
    description: 'Bosim ostida ishlovchi idishlarni (kimyo) qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_CHEMICAL_CONTAINER,
    icon: 'chemicalVessel',
  },
  {
    id: 31,
    title: 'Bug‘ va issiq suv quvurlarini qayta ro‘yxatga olish',
    name: 'Bug‘ va issiq suv quvuri',
    description: 'Bug‘ va issiq suv quvurlarini qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_HEAT_PIPELINE,
    icon: 'steamPipe',
  },
  {
    id: 32,
    title: 'Qozon utilizatorlarini qayta ro‘yxatga olish',
    name: 'Qozon utilizatorlarini',
    description: 'Qozon utilizatorlarini qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_BOILER_UTILIZER,
    icon: 'recycleBoiler',
  },
  {
    id: 33,
    title: 'Bosim ostida ishlovchi idishlarni (SUG) qayta ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idishlarni (SUG)',
    description: 'Bosim ostida ishlovchi idishlarni (SUG) qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_LPG_CONTAINER,
    icon: 'gasVessel',
  },
  {
    id: 34,
    title: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni qayta ro‘yxatga olish',
    name: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilma',
    description:
      'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_LPG_POWERED,
    icon: 'naturalGas',
  },
  {
    id: 35,
    title: 'Yuk ko‘targichni qayta ro‘yxatga olish',
    name: 'Yuk ko‘targich',
    description: 'Yuk ko‘targichni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_HOIST,
    icon: 'heavyLift',
  },
  {
    id: 36,
    title: 'Osma arqonli yuruvchi yo‘lni qayta ro‘yxatga olish',
    name: 'Osma arqonli yuruvchi yo‘l',
    description: 'Osma arqonli yuruvchi yo‘lni qayta ro‘yxatga olish ariza shakli',
    type: ApplicationTypeEnum.RE_REGISTER_CABLEWAY,
    icon: 'cableway',
  },
  {
    id: 37,
    title: 'Kranni ro‘yxatga olish',
    name: 'Kran',
    description: 'Kranni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CRANE,
    equipmentType: ApplicationTypeEnum.CRANE,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'crane',
  },
  {
    id: 38,
    title: 'Bosim ostida ishlovchi idishni ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish',
    description: 'Bosim ostida ishlovchi idishni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CONTAINER,
    equipmentType: ApplicationTypeEnum.CONTAINER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'pressureVessel',
  },
  {
    id: 39,
    title: 'Bug‘ qozonni ro‘yxatga olish',
    name: 'Bug‘ qozon',
    description: 'Bug‘ qozonlarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_BOILER,
    equipmentType: ApplicationTypeEnum.BOILER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'boiler',
  },
  {
    id: 40,
    title: 'Liftni ro‘yxatga olish',
    name: 'Lift',
    description: 'Liftni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_ELEVATOR,
    equipmentType: ApplicationTypeEnum.ELEVATOR,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'elevator',
  },
  {
    id: 41,
    title: 'Eskalatorni ro‘yxatga olish',
    name: 'Eskalator',
    description: 'Eskalatorni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_ESCALATOR,
    equipmentType: ApplicationTypeEnum.ESCALATOR,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'escalator',
  },
  {
    id: 42,
    title: 'Attraksionni ro‘yxatga olish',
    name: 'Attraksion',
    description: 'Attraksion qurilmalarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_ATTRACTION,
    equipmentType: ApplicationTypeEnum.ATTRACTION,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'attraction',
  },
  {
    id: 43,
    title: 'Quvurni ro‘yxatga olish',
    name: 'Quvur',
    description: 'Quvurlarni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_PIPELINE,
    equipmentType: ApplicationTypeEnum.PIPELINE,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'pipeSystem',
  },
  {
    id: 44,
    title: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish (kimyo)',
    description: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CHEMICAL_CONTAINER,
    equipmentType: ApplicationTypeEnum.CHEMICAL_CONTAINER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'chemicalVessel',
  },
  {
    id: 45,
    title: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish',
    name: 'Bug‘ va issiq suv quvuri',
    description: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_HEAT_PIPELINE,
    equipmentType: ApplicationTypeEnum.HEAT_PIPELINE,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'steamPipe',
  },
  {
    id: 46,
    title: 'Qozon utilizatorlarini ro‘yxatga olish',
    name: 'Qozon utilizatorlarini',
    description: 'Qozon utilizatorlarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_BOILER_UTILIZER,
    equipmentType: ApplicationTypeEnum.BOILER_UTILIZER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'recycleBoiler',
  },
  {
    id: 47,
    title: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idishlarni (SUG)',
    description: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_LPG_CONTAINER,
    equipmentType: ApplicationTypeEnum.LPG_CONTAINER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'gasVessel',
  },
  {
    id: 48,
    title: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish',
    name: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilma',
    description:
      'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_LPG_POWERED,
    equipmentType: ApplicationTypeEnum.LPG_POWERED,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'naturalGas',
  },
  {
    id: 49,
    title: 'Yuk ko‘targichni ro‘yxatga olish',
    name: 'Yuk ko‘targich',
    description: 'Yuk ko‘targichni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_HOIST,
    equipmentType: ApplicationTypeEnum.HOIST,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'heavyLift',
  },
  {
    id: 50,
    title: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    name: 'Osma arqonli yuruvchi yo‘l',
    description: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CABLEWAY,
    equipmentType: ApplicationTypeEnum.CABLEWAY,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'cableway',
  },
  {
    id: 51,
    title: 'Ionlashtiruvchi nurlanish manbalarini ro‘yxatga olish',
    description: 'Ionlashtiruvchi nurlanish manbalarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.INM,
    type: ApplicationTypeEnum.REGISTER_IRS,
    icon: 'radiationRegisterIcon',
  },
  {
    id: 52,
    title: 'Ionlashtiruvchi nurlanish manbalarini qabul qilish',
    description: 'Ionlashtiruvchi nurlanish manbalarini qabul qilish uchun ariza shakli',
    category: ApplicationCategory.INM,
    type: ApplicationTypeEnum.ACCEPT_IRS,
    icon: 'radiationReceiveIcon',
  },
  {
    id: 53,
    title: 'Ionlashtiruvchi nurlanish manbalarini topshirish',
    description: 'Ionlashtiruvchi nurlanish manbalarini topshirish uchun ariza shakli',
    category: ApplicationCategory.INM,
    type: ApplicationTypeEnum.TRANSFER_IRS,
    icon: 'radiationTransferIcon',
  },
  {
    id: 54,
    title: 'Rentgenni ro‘yxatga olish',
    description: 'Rentgenni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.XRAY,
    type: ApplicationTypeEnum.REGISTER_XRAY,
    icon: 'radiationRegisterIcon',
  },
  {
    id: 55,
    title: 'Rentgenni ro‘yxatga olish',
    description: 'Rentgenni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.ILLEGAL_XRAY,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_XRAY,
    icon: 'radiationRegisterIcon',
  },
  {
    id: 56,
    title: "Ekspert tashkilotini akkreditatsiyadan o'tkazish",
    description: "Ekspert tashkilotini akkreditatsiyadan o'tkazish uchun ariza",
    category: ApplicationCategory.ACCREDITATION,
    type: ApplicationTypeEnum.REGISTER_ACCREDITATION,
    icon: 'expertOrgAccreditationIcon',
  },
  {
    id: 57,
    title: "Ekspert tashkilotini qayta akkreditatsiyadan o'tkazish",
    description: "Ekspert tashkilotini qayta akkreditatsiyadan o'tkazish uchun ariza",
    category: ApplicationCategory.ACCREDITATION,
    type: ApplicationTypeEnum.RE_REGISTER_ACCREDITATION,
    icon: 'expertOrgAccreditationIcon',
  },
  {
    id: 58,
    title: 'Ekspert tashkilotining akkreditatsiya sohasini kengaytirish',
    description: 'Ekspert tashkilotining akkreditatsiya sohasini kengaytirish uchun ariza',
    category: ApplicationCategory.ACCREDITATION,
    type: ApplicationTypeEnum.EXPAND_ACCREDITATION,
    icon: 'expertOrgAccreditationIcon',
  },
  {
    id: 59,
    title: 'Sanoat xavfsizligi ekspertiza xulosalarini ro‘yxatga olish',
    description: 'Sanoat xavfsizligi ekspertiza xulosalarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.ACCREDITATION,
    type: ApplicationTypeEnum.REGISTER_EXPERTISE_CONCLUSION,
    icon: 'industrialSafetyExpertiseRegistrationIcon',
  },
  {
    id: 60,
    title: 'XICHO xodimlarini attestatsiyadan o‘tkazish',
    description: 'XICHO xodimlarini attestatsiyadan o‘tkazish ariza shakli',
    category: ApplicationCategory.ATTESTATION_PREVENTION,
    type: ApplicationTypeEnum.REGISTER_ATTESTATION,
    icon: 'staffAttestationIcon',
  },
  {
    id: 61,
    title: 'XICHO rahbar xodimlarini attestatsiyadan o‘tkazish',
    description: 'XICHO xodimlarini attestatsiyadan o‘tkazish ariza shakli',
    category: ApplicationCategory.DEFAULT,
    type: ApplicationTypeEnum.ATTESTATION_COMMITTEE,
    icon: 'staffAttestationIcon',
  },
  {
    id: 62,
    title: 'XICHO muhandis-texnik va oddiy xodimlarini attestatsiyadan o‘tkazish',
    description: 'XICHO xodimlarini attestatsiyadan o‘tkazish ariza shakli',
    category: ApplicationCategory.DEFAULT,
    type: ApplicationTypeEnum.ATTESTATION_REGIONAL,
    icon: 'staffAttestationIcon',
  },
  {
    id: 63,
    title: 'TXYZ kadastr pasportini ro‘yxatga olish',
    description: 'TXYZ kadastr pasportini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.CADASTRE,
    type: ApplicationTypeEnum.REGISTER_CADASTRE_PASSPORT,
    icon: 'staffAttestationIcon',
  },
  {
    id: 64,
    title: 'Sanoat xavfsizligi deklaratsiyasini ro‘yxatga olish',
    description: 'Sanoat xavfsizligi deklaratsiyasini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.CADASTRE,
    type: ApplicationTypeEnum.REGISTER_DECLARATION,
    icon: 'staffAttestationIcon',
  },
  {
    id: 65,
    title: 'Kranni ro‘yxatga olish arizasi',
    name: 'Kran',
    description: 'Kranni ro‘yxatga olish arizasi',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CRANE,
    icon: 'crane',
  },
  {
    id: 66,
    title: 'Bosim ostida ishlovchi idishni ro‘yxatga olish',
    name: 'Container',
    description: 'Bosim ostida ishlovchi idishni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CONTAINER,
    icon: 'pressureVessel',
  },
  {
    id: 67,
    title: 'Bug‘ qozonni ro‘yxatga olish',
    name: 'Bug‘ qozon',
    description: 'Bug‘ qozonni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_BOILER,
    icon: 'boiler',
  },
  {
    id: 68,
    title: 'Liftni ro‘yxatga olish',
    name: 'Lift',
    description: 'Liftni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_ELEVATOR,
    icon: 'elevator',
  },
  {
    id: 69,
    title: 'Eskalatorni ro‘yxatga olish',
    name: 'Eskalator',
    description: 'Eskalatorni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_ESCALATOR,
    icon: 'escalator',
  },
  {
    id: 70,
    title: 'Atraksion ro‘yxatga olish',
    name: 'Attraksion pasporti',
    description: 'Atraksion ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_ATTRACTION_PASSPORT,
    icon: 'passport',
  },
  {
    id: 71,
    title: 'Quvurlarni ro‘yxatga olish ariza shakli',
    name: 'Quvur',
    description: 'Quvurlarni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_PIPELINE,
    icon: 'pipeSystem',
  },
  {
    id: 72,
    title: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish (kimyo)',
    description: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CHEMICAL_CONTAINER,
    icon: 'chemicalVessel',
  },
  {
    id: 73,
    title: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish',
    name: 'Bug‘ va issiq suv quvuri',
    description: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_HEAT_PIPELINE,
    icon: 'steamPipe',
  },
  {
    id: 74,
    title: 'Qozon utilizatorlarini ro‘yxatga olish',
    name: 'Qozon utilizatorlarini',
    description: 'Qozon utilizatorlarini ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_BOILER_UTILIZER,
    icon: 'recycleBoiler',
  },
  {
    id: 75,
    title: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idishlarni (SUG)',
    description: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_LPG_CONTAINER,
    icon: 'gasVessel',
  },
  {
    id: 76,
    title: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish',
    name: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilma',
    description: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_LPG_POWERED,
    icon: 'naturalGas',
  },
  {
    id: 77,
    title: 'Yuk ko‘targichni ro‘yxatga olish',
    name: 'Yuk ko‘targichni ro‘yxatga olish',
    description: 'Yiliga Yuk ko‘targichni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_HOIST,
    icon: 'heavyLift',
  },
  {
    id: 78,
    title: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    name: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    description: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CABLEWAY,
    icon: 'cableway',
  },
  {
    id: 79,
    title: 'XICHO reyestriga o‘zgartirish kiritish',
    description: 'XICHO reyestriga o‘zgartirish kiritish uchun ariza shakli',
    category: ApplicationCategory.ILLEGAL,
    type: ApplicationTypeEnum.RE_REGISTER_ILLEGAL_HF,
    icon: 'factoryRegisterIcon',
  },
]
