import {
  ApplicationCardItem,
  ApplicationCategory,
  ApplicationTypeEnum,
  MainApplicationCategory,
} from '@/entities/create-application'
import { FileInput, FileOutput, FilePlus } from 'lucide-react'

export const APPLICATION_CATEGORIES = [
  {
    id: ApplicationCategory.HF,
    name: 'XICHO',
  },
  {
    id: ApplicationCategory.EQUIPMENTS,
    name: 'Xavfli obyektlar va qurilmalar',
  },
  {
    id: ApplicationCategory.IRS,
    name: 'INM',
  },
  {
    id: ApplicationCategory.XRAY,
    name: 'Rentgen',
  },
]

export const MAIN_APPLICATION_BY_CATEGORY = {
  [ApplicationCategory.HF]: [],
  [ApplicationCategory.EQUIPMENTS]: [
    {
      id: MainApplicationCategory.REGISTER,
      title: 'Xavfli obyekt va qurilmalarni ro‘yxatga olish',
      description: 'Xavfli obyekt va qurilmalarni davlat ro‘yxatiga olish ariza shakllari',
      icon: FileInput,
    },
    {
      id: MainApplicationCategory.UNREGISTER,
      title: 'Xavfli obyekt va qurilmalarni ro‘yxatdan chiqarish',
      description: 'Xavfli obyekt va qurilmalarni ro‘yxatdan chiqarish ariza shakllari',
      icon: FileOutput,
    },
    {
      id: MainApplicationCategory.REREGISTER,
      title: 'Xavfli obyekt va qurilmalarni qayta ro‘yxatdan o‘tkazish',
      description: 'Xavfli obyekt va qurilmalarni qayta ro‘yxatdan o‘tkazish ariza shakllari',
      icon: FilePlus,
    },
  ],
  [ApplicationCategory.IRS]: [],
  [ApplicationCategory.XRAY]: [],
  [ApplicationCategory.ILLEGAL_HF]: [],
}

export const REPORTS_DATA: ApplicationCardItem[] = [
  {
    id: 1,
    title: '1-hisobot',
    description: 'Jismoniy va yuridik shaxslardan yuborilgan arizalarni hududlar kesimida taqsimlanishi',
    type: ApplicationTypeEnum.REPORT_1,
    icon: 'factoryRegisterIcon',
  },
  {
    id: 2,
    title: '2-hisobot',
    description:
      'Jismoniy va yuridik shaxslardan yuborilgan arizalarni turlari bo‘yicha hududlar kesimida taqsimlanishi',
    type: ApplicationTypeEnum.REPORT_2,
    icon: 'factoryDeregisterIcon',
  },
  {
    id: 3,
    title: '3-hisobot',
    description:
      'Davlat ro‘yxatiga kiritilgan va ro‘yxatdan chiqarilgan XICHO, qurilmalar va IIMlarni hududlar kesimida taqsimlanishi',
    type: ApplicationTypeEnum.REPORT_3,
    icon: 'factoryUpdateIcon',
  },
  {
    id: 4,
    title: '4-hisobot',
    description:
      'Davlat ro‘yxatidan o‘tqazilgan amaldagi XICHO, INM, Bosim ostidagi idishlar va qurilmalar to‘g‘risida sanalar bo‘yicha maʼlumot',
    type: ApplicationTypeEnum.REPORT_4,
    icon: 'escalator',
  },
]

export const APPLICATIONS_DATA: ApplicationCardItem[] = [
  {
    id: 5,
    title: 'Qurilmani ro‘yxatdan chiqarish',
    name: 'Qurilma',
    description: 'Qurilmani ro‘yxatdan chiqarish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.DEREGISTER_EQUIPMENT,
    parentId: MainApplicationCategory.UNREGISTER,
    icon: 'boiler',
  },
  {
    id: 6,
    title: 'Qurilmani qayta ro‘yxatga olish',
    name: 'Qurilma',
    description: 'Qurilmani qayta ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.RE_REGISTER_EQUIPMENT,
    parentId: MainApplicationCategory.REREGISTER,
    icon: 'boiler',
  },
  {
    id: 37,
    title: 'Kranni ro‘yxatga olish',
    name: 'Kran',
    description: 'Kranni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CRANE,
    equipmentType: ApplicationTypeEnum.CRANE,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'crane',
  },
  {
    id: 38,
    title: 'Bosim ostida ishlovchi idishni ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish',
    description: 'Bosim ostida ishlovchi idishni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CONTAINER,
    equipmentType: ApplicationTypeEnum.CONTAINER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'pressureVessel',
  },
  {
    id: 39,
    title: 'Bug‘ qozonni ro‘yxatga olish',
    name: 'Bug‘ qozon',
    description: 'Bug‘ qozonlarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_BOILER,
    equipmentType: ApplicationTypeEnum.BOILER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'boiler',
  },
  {
    id: 40,
    title: 'Liftni ro‘yxatga olish',
    name: 'Lift',
    description: 'Liftni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_ELEVATOR,
    equipmentType: ApplicationTypeEnum.ELEVATOR,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'elevator',
  },
  {
    id: 41,
    title: 'Eskalatorni ro‘yxatga olish',
    name: 'Eskalator',
    description: 'Eskalatorni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_ESCALATOR,
    equipmentType: ApplicationTypeEnum.ESCALATOR,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'escalator',
  },
  {
    id: 42,
    title: 'Attraksionni ro‘yxatga olish',
    name: 'Attraksion',
    description: 'Attraksion qurilmalarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_ATTRACTION,
    equipmentType: ApplicationTypeEnum.ATTRACTION,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'attraction',
  },
  {
    id: 43,
    title: 'Quvurni ro‘yxatga olish',
    name: 'Quvur',
    description: 'Quvurlarni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_PIPELINE,
    equipmentType: ApplicationTypeEnum.PIPELINE,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'pipeSystem',
  },
  {
    id: 44,
    title: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish (kimyo)',
    description: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CHEMICAL_CONTAINER,
    equipmentType: ApplicationTypeEnum.CHEMICAL_CONTAINER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'chemicalVessel',
  },
  {
    id: 45,
    title: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish',
    name: 'Bug‘ va issiq suv quvuri',
    description: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_HEAT_PIPELINE,
    equipmentType: ApplicationTypeEnum.HEAT_PIPELINE,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'steamPipe',
  },
  {
    id: 46,
    title: 'Qozon utilizatorlarini ro‘yxatga olish',
    name: 'Qozon utilizatorlarini',
    description: 'Qozon utilizatorlarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_BOILER_UTILIZER,
    equipmentType: ApplicationTypeEnum.BOILER_UTILIZER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'recycleBoiler',
  },
  {
    id: 47,
    title: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idishlarni (SUG)',
    description: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_LPG_CONTAINER,
    equipmentType: ApplicationTypeEnum.LPG_CONTAINER,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'gasVessel',
  },
  {
    id: 48,
    title: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish',
    name: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilma',
    description:
      'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_LPG_POWERED,
    equipmentType: ApplicationTypeEnum.LPG_POWERED,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'naturalGas',
  },
  {
    id: 49,
    title: 'Yuk ko‘targichni ro‘yxatga olish',
    name: 'Yuk ko‘targich',
    description: 'Yuk ko‘targichni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_HOIST,
    equipmentType: ApplicationTypeEnum.HOIST,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'heavyLift',
  },
  {
    id: 50,
    title: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    name: 'Osma arqonli yuruvchi yo‘l',
    description: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.EQUIPMENTS,
    type: ApplicationTypeEnum.REGISTER_CABLEWAY,
    equipmentType: ApplicationTypeEnum.CABLEWAY,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'cableway',
  },
  {
    id: 1,
    title: 'XICHOni ro‘yxatga olish',
    description: 'XICHOni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.HF,
    type: ApplicationTypeEnum.REGISTER_HF,
    icon: 'factoryRegisterIcon',
  },
  {
    id: 3,
    title: 'XICHOni ro‘yxatdan chiqarish',
    description: 'XICHOni ro‘yxatdan chiqarish ariza shakli',
    category: ApplicationCategory.HF,
    type: ApplicationTypeEnum.DEREGISTER_HF,
    icon: 'factoryDeregisterIcon',
  },
  {
    id: 65,
    title: 'Kranni ro‘yxatga olish arizasi',
    name: 'Kran',
    description: 'Kranni ro‘yxatga olish arizasi',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CRANE,
    icon: 'crane',
  },
  {
    id: 66,
    title: 'Bosim ostida ishlovchi idishni ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish',
    description: 'Bosim ostida ishlovchi idishni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CONTAINER,
    icon: 'pressureVessel',
  },
  {
    id: 67,
    title: 'Bug‘ qozonni ro‘yxatga olish',
    name: 'Bug‘ qozon',
    description: 'Bug‘ qozonni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_BOILER,
    icon: 'boiler',
  },
  {
    id: 68,
    title: 'Liftni ro‘yxatga olish',
    name: 'Lift',
    description: 'Liftni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_ELEVATOR,
    icon: 'elevator',
  },
  {
    id: 69,
    title: 'Eskalatorni ro‘yxatga olish',
    name: 'Eskalator',
    description: 'Eskalatorni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_ESCALATOR,
    icon: 'escalator',
  },
  {
    id: 70,
    title: 'Atraksion ro‘yxatga olish',
    name: 'Attraksion pasporti',
    description: 'Atraksion ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_ATTRACTION,
    icon: 'passport',
  },
  {
    id: 71,
    title: 'Quvurlarni ro‘yxatga olish ariza shakli',
    name: 'Quvur',
    description: 'Quvurlarni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_PIPELINE,
    icon: 'pipeSystem',
  },
  {
    id: 72,
    title: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idish (kimyo)',
    description: 'Bosim ostida ishlovchi idishlarni (kimyo) ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CHEMICAL_CONTAINER,
    icon: 'chemicalVessel',
  },
  {
    id: 73,
    title: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish',
    name: 'Bug‘ va issiq suv quvuri',
    description: 'Bug‘ va issiq suv quvurlarini ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_HEAT_PIPELINE,
    icon: 'steamPipe',
  },
  {
    id: 74,
    title: 'Qozon utilizatorlarini ro‘yxatga olish',
    name: 'Qozon utilizatorlarini',
    description: 'Qozon utilizatorlarini ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_BOILER_UTILIZER,
    icon: 'recycleBoiler',
  },
  {
    id: 75,
    title: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish',
    name: 'Bosim ostida ishlovchi idishlarni (SUG)',
    description: 'Bosim ostida ishlovchi idishlarni (SUG) ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_LPG_CONTAINER,
    icon: 'gasVessel',
  },
  {
    id: 76,
    title: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish',
    name: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilma',
    description: 'Yiliga 100 ming va undan ortiq kubometr tabiiy gazdan foydalanuvchi qurilmalarni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_LPG_POWERED,
    icon: 'naturalGas',
  },
  {
    id: 77,
    title: 'Yuk ko‘targichni ro‘yxatga olish',
    name: 'Yuk ko‘targichni ro‘yxatga olish',
    description: 'Yiliga Yuk ko‘targichni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_HOIST,
    icon: 'heavyLift',
  },
  {
    id: 78,
    title: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    name: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    description: 'Osma arqonli yuruvchi yo‘lni ro‘yxatga olish',
    category: ApplicationCategory.ILLEGAL_EQUIPMENTS,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_CABLEWAY,
    icon: 'cableway',
  },
  {
    id: 2,
    title: 'XICHOni ro‘yxatga olish',
    description: 'XICHOni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.ILLEGAL_HF,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_HF,
    icon: 'factoryRegisterIcon',
  },
  {
    id: 55,
    title: 'Rentgenni ro‘yxatga olish',
    description: 'Rentgenni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.ILLEGAL_XRAY,
    type: ApplicationTypeEnum.ILLEGAL_REGISTER_XRAY,
    icon: 'radiationRegisterIcon',
  },
  {
    id: 51,
    title: 'Ionlashtiruvchi nurlanish manbalarini ro‘yxatga olish',
    description: 'Ionlashtiruvchi nurlanish manbalarini ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.IRS,
    type: ApplicationTypeEnum.REGISTER_IRS,
    icon: 'radiationRegisterIcon',
  },
  {
    id: 52,
    title: 'Ionlashtiruvchi nurlanish manbalarini qabul qilish',
    description: 'Ionlashtiruvchi nurlanish manbalarini qabul qilish uchun ariza shakli',
    category: ApplicationCategory.IRS,
    type: ApplicationTypeEnum.ACCEPT_IRS,
    icon: 'radiationReceiveIcon',
  },
  {
    id: 53,
    title: 'Ionlashtiruvchi nurlanish manbalarini topshirish',
    description: 'Ionlashtiruvchi nurlanish manbalarini topshirish uchun ariza shakli',
    category: ApplicationCategory.IRS,
    type: ApplicationTypeEnum.TRANSFER_IRS,
    icon: 'radiationTransferIcon',
  },
  {
    id: 54,
    title: 'Rentgenni ro‘yxatga olish',
    description: 'Rentgenni ro‘yxatga olish ariza shakli',
    category: ApplicationCategory.XRAY,
    type: ApplicationTypeEnum.REGISTER_XRAY,
    icon: 'radiationRegisterIcon',
  },
]
