import { ApplicationCardItem, ApplicationCategory, MainApplicationCategory } from '@/entities/create-application';
import { ApplicationTypeEnum } from '@/entities/user/applications/create-application/model/application.types';

export const APPLICATION_CATEGORIES = [
  {
    id: ApplicationCategory.XICHO,
    name: 'XICHO',
  },
  {
    id: ApplicationCategory.HOKQ,
    name: 'Хавфли объектлар ва қурилмалар',
  },
  {
    id: ApplicationCategory.INM,
    name: 'ИНМ',
  },
  {
    id: ApplicationCategory.ACCREDITATION,
    name: 'Аккредитация',
  },
  {
    id: ApplicationCategory.ATTESTATION_PREVENTION,
    name: 'Аттестация ва профилактика',
  },
  {
    id: ApplicationCategory.CADASTRE,
    name: 'Кадастр',
  },
];

export const MAIN_APPLICATION_BY_CATEGORY = {
  [ApplicationCategory.HOKQ]: [
    {
      id: MainApplicationCategory.REGISTER,
      title: 'Хавфли объект ва қурилмаларни рўйхатга олиш',
      description: 'Хавфли объектларни давлат рўйхатига киритиш учун ариза',
      icon: 'documentAdd',
    },
    {
      id: MainApplicationCategory.UNREGISTER,
      title: 'Хавфли объект ва қурилмаларни рўйхатдан чиқариш',
      description: 'Объектларни рўйхатдан чиқариш учун ариза',
      icon: 'documentRemove',
    },
    {
      id: MainApplicationCategory.REREGISTER,
      title: 'Хавфли объект ва қурилмаларни қайта рўйхатдан ўтказиш',
      description: 'Объектларни қайта рўйхатдан ўтказиш учун ариза',
      icon: 'documentRefresh',
    },
  ],
  [ApplicationCategory.INM]: [],
  [ApplicationCategory.XICHO]: [],
  [ApplicationCategory.CADASTRE]: [],
  [ApplicationCategory.ACCREDITATION]: [],
  [ApplicationCategory.ATTESTATION_PREVENTION]: [],
};

export const APPLICATIONS_DATA: ApplicationCardItem[] = [
  {
    id: 10,
    title: 'Кранни рўйхатга олиш',
    description: 'Кран қурилмаларини рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterCrane,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'crane',
  },
  {
    id: 4,
    title: 'Босим остида ишловчи идишни рўйхатга олиш',
    description: 'Босим остида ишлайдиган идишларни рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterVessel,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'pressureVessel',
  },
  {
    id: 5,
    title: 'Буғқозонни рўйхатга олиш',
    description: 'Буғ қозонларини рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterSteamAndHotWaterPipeline,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'boiler',
  },
  {
    id: 6,
    title: 'Лифтни рўйхатга олиш',
    description: 'Лифт қурилмаларини рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterLift,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'elevator',
  },
  {
    id: 7,
    title: 'Эскалаторни рўйхатга олиш',
    description: 'Эскалатор қурилмаларини рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterEscalator,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'escalator',
  },
  {
    id: 8,
    title: 'Аттракцион паспортини рўйхатга олиш',
    description: 'Аттракцион паспортларини расмийлаштириш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterAttractionPassport,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'passport',
  },
  {
    id: 9,
    title: 'Аттракционни рўйхатга олиш',
    description: 'Аттракцион қурилмаларини рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterAttraction,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'attraction',
  },
  {
    id: 11,
    title: 'Қувурни рўйхатга олиш',
    description: 'Қувурларни рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterPipeline,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'pipeSystem',
  },
  {
    id: 12,
    title: 'Босим остида ишловчи идишларни (кимё) рўйхатга олиш',
    description: 'Босим остида ишловчи идишларни (кимё) рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterPressureVesselChemical,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'chemicalVessel',
  },
  {
    id: 13,
    title: 'Буғ ва иссиқ сув қувурларини рўйхатга олиш',
    description: 'Буғ ва иссиқ сув қувурларини рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterSteamAndHotWaterPipeline,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'steamPipe',
  },
  {
    id: 14,
    title: 'Қозон утилизаторларини рўйхатга олиш',
    description: 'Қозон утилизаторларини рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterBoilerUtilizer,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'recycleBoiler',
  },
  {
    id: 15,
    title: 'Босим остида ишловчи идишларни (СУГ) рўйхатга олиш',
    description: 'Босим остида ишловчи идишларни (СУГ) рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterPressureVesselLPG,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'gasVessel',
  },
  {
    id: 16,
    title: 'Йилига 100 минг ва ундан ортиқ кубометр табиий газдан фойдаланувчи қурилмаларни рўйхатга олиш',
    description:
      'Йилига 100 минг ва ундан ортиқ кубометр табиий газдан фойдаланувчи қурилмаларни рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterHighGasUsageEquipment,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'naturalGas',
  },
  {
    id: 17,
    title: 'Юк кўтаргични рўйхатга олиш',
    description: 'Юк кўтаргични рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterElevator,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'heavyLift',
  },
  {
    id: 18,
    title: 'Осма арқонли юрувчи йўлни рўйхатга олиш',
    description: 'Осма арқонли юрувчи йўлни рўйхатга олиш учун ариза',
    category: ApplicationCategory.HOKQ,
    type: ApplicationTypeEnum.RegisterBridgeOrRoad,
    parentId: MainApplicationCategory.REGISTER,
    icon: 'cableway',
  },
];
