export enum UserRoles {
  LEGAL = 'LEGAL',
  HEAD = 'HEAD',
  ADMIN = 'ROLE_SUPER_ADMIN',
  MANAGER = 'MANAGER',
  CHAIRMAN = 'CHAIRMAN',
  REGIONAL = 'REGIONAL',
  INSPECTOR = 'INSPECTOR',
  INDIVIDUAL = 'INDIVIDUAL',
}
