export const API_ENDPOINTS: Record<string, string> = {
  LOGIN: '/auth/login',
  LOGOUT: '/auth/logout',
  USER_ME: '/users/me',
  USERS: '/users',
  REGIONS: '/regions',
  REGIONS_SELECT: '/regions/select',
  DISTRICTS: '/districts',
  DISTRICT_SELECT: '/districts/select',
  DEPARTMENTS: '/departments',
  DEPARTMENT_SELECT: '/departments/select',
  OFFICES: '/offices',
  OFFICE_SELECT: '/offices/select',
  OFFICE_USERS: '/users/office-users',
  COMMITTEE_USERS: '/users/committee-users',
};
