export const API_ENDPOINTS: Record<string, string> = {
  LOGIN: '/auth/login',
  LOGIN_ONE_ID: '/auth/one-id',
  LOGOUT: '/auth/logout',
  USER_ME: '/users/me',
  USERS: '/users',
  REGIONS: '/regions',
  REGIONS_SELECT: '/regions/select',
  DISTRICTS: '/districts',
  DISTRICT_SELECT: '/districts/select',
  DEPARTMENTS: '/departments',
  DEPARTMENT_SELECT: '/departments/select',
  OFFICES: '/offices',
  OFFICE_SELECT: '/offices/select',
  OFFICE_USERS: '/users/office-users',
  COMMITTEE_USERS: '/users/committee-users',
  HAZARDOUS_FACILITY_TYPES: '/hf-types',
  HAZARDOUS_FACILITY_TYPES_SELECT: '/hf-types/select',
  APPEAL_HF: '/appeals/hf',
  TEMPLATES: '/templates',
  UPDATE_TEMPLATE_CONTENT: '/templates/content',
  EQUIPMENT_CRANE: '/appeals/equipment/crane',
};
